/**
 *
 *  AccountTransferStandingInstructionsHistory.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AccountTransferStandingInstructionsHistory.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::TlCustomerDb;

const std::string AccountTransferStandingInstructionsHistory::Cols::_id = "\"id\"";
const std::string AccountTransferStandingInstructionsHistory::Cols::_business_id = "\"business_id\"";
const std::string AccountTransferStandingInstructionsHistory::Cols::_standing_instruction_id = "\"standing_instruction_id\"";
const std::string AccountTransferStandingInstructionsHistory::Cols::_status = "\"status\"";
const std::string AccountTransferStandingInstructionsHistory::Cols::_execution_time = "\"execution_time\"";
const std::string AccountTransferStandingInstructionsHistory::Cols::_amount = "\"amount\"";
const std::string AccountTransferStandingInstructionsHistory::Cols::_error_log = "\"error_log\"";
const std::string AccountTransferStandingInstructionsHistory::primaryKeyName = "id";
const bool AccountTransferStandingInstructionsHistory::hasPrimaryKey = true;
const std::string AccountTransferStandingInstructionsHistory::tableName = "\"account_transfer_standing_instructions_history\"";

const std::vector<typename AccountTransferStandingInstructionsHistory::MetaData> AccountTransferStandingInstructionsHistory::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"business_id","std::string","uuid",0,0,0,0},
{"standing_instruction_id","std::string","uuid",0,0,0,1},
{"status","std::string","character varying",20,0,0,1},
{"execution_time","::trantor::Date","timestamp without time zone",0,0,0,0},
{"amount","std::string","numeric",0,0,0,1},
{"error_log","std::string","character varying",500,0,0,0}
};
const std::string &AccountTransferStandingInstructionsHistory::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AccountTransferStandingInstructionsHistory::AccountTransferStandingInstructionsHistory(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["business_id"].isNull())
        {
            businessId_=std::make_shared<std::string>(r["business_id"].as<std::string>());
        }
        if(!r["standing_instruction_id"].isNull())
        {
            standingInstructionId_=std::make_shared<std::string>(r["standing_instruction_id"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["execution_time"].isNull())
        {
            auto timeStr = r["execution_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                executionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["amount"].isNull())
        {
            amount_=std::make_shared<std::string>(r["amount"].as<std::string>());
        }
        if(!r["error_log"].isNull())
        {
            errorLog_=std::make_shared<std::string>(r["error_log"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            businessId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            standingInstructionId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                executionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            amount_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            errorLog_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

AccountTransferStandingInstructionsHistory::AccountTransferStandingInstructionsHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            businessId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            standingInstructionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                executionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            amount_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            errorLog_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

AccountTransferStandingInstructionsHistory::AccountTransferStandingInstructionsHistory(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("business_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["business_id"].isNull())
        {
            businessId_=std::make_shared<std::string>(pJson["business_id"].asString());
        }
    }
    if(pJson.isMember("standing_instruction_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["standing_instruction_id"].isNull())
        {
            standingInstructionId_=std::make_shared<std::string>(pJson["standing_instruction_id"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("execution_time"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["execution_time"].isNull())
        {
            auto timeStr = pJson["execution_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                executionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("amount"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["amount"].isNull())
        {
            amount_=std::make_shared<std::string>(pJson["amount"].asString());
        }
    }
    if(pJson.isMember("error_log"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["error_log"].isNull())
        {
            errorLog_=std::make_shared<std::string>(pJson["error_log"].asString());
        }
    }
}

void AccountTransferStandingInstructionsHistory::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            businessId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            standingInstructionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                executionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            amount_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            errorLog_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

void AccountTransferStandingInstructionsHistory::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("business_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["business_id"].isNull())
        {
            businessId_=std::make_shared<std::string>(pJson["business_id"].asString());
        }
    }
    if(pJson.isMember("standing_instruction_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["standing_instruction_id"].isNull())
        {
            standingInstructionId_=std::make_shared<std::string>(pJson["standing_instruction_id"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("execution_time"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["execution_time"].isNull())
        {
            auto timeStr = pJson["execution_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                executionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("amount"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["amount"].isNull())
        {
            amount_=std::make_shared<std::string>(pJson["amount"].asString());
        }
    }
    if(pJson.isMember("error_log"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["error_log"].isNull())
        {
            errorLog_=std::make_shared<std::string>(pJson["error_log"].asString());
        }
    }
}

const std::string &AccountTransferStandingInstructionsHistory::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AccountTransferStandingInstructionsHistory::getId() const noexcept
{
    return id_;
}
void AccountTransferStandingInstructionsHistory::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void AccountTransferStandingInstructionsHistory::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename AccountTransferStandingInstructionsHistory::PrimaryKeyType & AccountTransferStandingInstructionsHistory::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &AccountTransferStandingInstructionsHistory::getValueOfBusinessId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(businessId_)
        return *businessId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AccountTransferStandingInstructionsHistory::getBusinessId() const noexcept
{
    return businessId_;
}
void AccountTransferStandingInstructionsHistory::setBusinessId(const std::string &pBusinessId) noexcept
{
    businessId_ = std::make_shared<std::string>(pBusinessId);
    dirtyFlag_[1] = true;
}
void AccountTransferStandingInstructionsHistory::setBusinessId(std::string &&pBusinessId) noexcept
{
    businessId_ = std::make_shared<std::string>(std::move(pBusinessId));
    dirtyFlag_[1] = true;
}
void AccountTransferStandingInstructionsHistory::setBusinessIdToNull() noexcept
{
    businessId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &AccountTransferStandingInstructionsHistory::getValueOfStandingInstructionId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(standingInstructionId_)
        return *standingInstructionId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AccountTransferStandingInstructionsHistory::getStandingInstructionId() const noexcept
{
    return standingInstructionId_;
}
void AccountTransferStandingInstructionsHistory::setStandingInstructionId(const std::string &pStandingInstructionId) noexcept
{
    standingInstructionId_ = std::make_shared<std::string>(pStandingInstructionId);
    dirtyFlag_[2] = true;
}
void AccountTransferStandingInstructionsHistory::setStandingInstructionId(std::string &&pStandingInstructionId) noexcept
{
    standingInstructionId_ = std::make_shared<std::string>(std::move(pStandingInstructionId));
    dirtyFlag_[2] = true;
}

const std::string &AccountTransferStandingInstructionsHistory::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AccountTransferStandingInstructionsHistory::getStatus() const noexcept
{
    return status_;
}
void AccountTransferStandingInstructionsHistory::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[3] = true;
}
void AccountTransferStandingInstructionsHistory::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[3] = true;
}

const ::trantor::Date &AccountTransferStandingInstructionsHistory::getValueOfExecutionTime() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(executionTime_)
        return *executionTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &AccountTransferStandingInstructionsHistory::getExecutionTime() const noexcept
{
    return executionTime_;
}
void AccountTransferStandingInstructionsHistory::setExecutionTime(const ::trantor::Date &pExecutionTime) noexcept
{
    executionTime_ = std::make_shared<::trantor::Date>(pExecutionTime);
    dirtyFlag_[4] = true;
}
void AccountTransferStandingInstructionsHistory::setExecutionTimeToNull() noexcept
{
    executionTime_.reset();
    dirtyFlag_[4] = true;
}

const std::string &AccountTransferStandingInstructionsHistory::getValueOfAmount() const noexcept
{
    static const std::string defaultValue = std::string();
    if(amount_)
        return *amount_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AccountTransferStandingInstructionsHistory::getAmount() const noexcept
{
    return amount_;
}
void AccountTransferStandingInstructionsHistory::setAmount(const std::string &pAmount) noexcept
{
    amount_ = std::make_shared<std::string>(pAmount);
    dirtyFlag_[5] = true;
}
void AccountTransferStandingInstructionsHistory::setAmount(std::string &&pAmount) noexcept
{
    amount_ = std::make_shared<std::string>(std::move(pAmount));
    dirtyFlag_[5] = true;
}

const std::string &AccountTransferStandingInstructionsHistory::getValueOfErrorLog() const noexcept
{
    static const std::string defaultValue = std::string();
    if(errorLog_)
        return *errorLog_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AccountTransferStandingInstructionsHistory::getErrorLog() const noexcept
{
    return errorLog_;
}
void AccountTransferStandingInstructionsHistory::setErrorLog(const std::string &pErrorLog) noexcept
{
    errorLog_ = std::make_shared<std::string>(pErrorLog);
    dirtyFlag_[6] = true;
}
void AccountTransferStandingInstructionsHistory::setErrorLog(std::string &&pErrorLog) noexcept
{
    errorLog_ = std::make_shared<std::string>(std::move(pErrorLog));
    dirtyFlag_[6] = true;
}
void AccountTransferStandingInstructionsHistory::setErrorLogToNull() noexcept
{
    errorLog_.reset();
    dirtyFlag_[6] = true;
}

void AccountTransferStandingInstructionsHistory::updateId(const uint64_t id)
{
}

const std::vector<std::string> &AccountTransferStandingInstructionsHistory::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "business_id",
        "standing_instruction_id",
        "status",
        "execution_time",
        "amount",
        "error_log"
    };
    return inCols;
}

void AccountTransferStandingInstructionsHistory::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusinessId())
        {
            binder << getValueOfBusinessId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStandingInstructionId())
        {
            binder << getValueOfStandingInstructionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExecutionTime())
        {
            binder << getValueOfExecutionTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAmount())
        {
            binder << getValueOfAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getErrorLog())
        {
            binder << getValueOfErrorLog();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AccountTransferStandingInstructionsHistory::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void AccountTransferStandingInstructionsHistory::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusinessId())
        {
            binder << getValueOfBusinessId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStandingInstructionId())
        {
            binder << getValueOfStandingInstructionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExecutionTime())
        {
            binder << getValueOfExecutionTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAmount())
        {
            binder << getValueOfAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getErrorLog())
        {
            binder << getValueOfErrorLog();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AccountTransferStandingInstructionsHistory::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusinessId())
    {
        ret["business_id"]=getValueOfBusinessId();
    }
    else
    {
        ret["business_id"]=Json::Value();
    }
    if(getStandingInstructionId())
    {
        ret["standing_instruction_id"]=getValueOfStandingInstructionId();
    }
    else
    {
        ret["standing_instruction_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getExecutionTime())
    {
        ret["execution_time"]=getExecutionTime()->toDbStringLocal();
    }
    else
    {
        ret["execution_time"]=Json::Value();
    }
    if(getAmount())
    {
        ret["amount"]=getValueOfAmount();
    }
    else
    {
        ret["amount"]=Json::Value();
    }
    if(getErrorLog())
    {
        ret["error_log"]=getValueOfErrorLog();
    }
    else
    {
        ret["error_log"]=Json::Value();
    }
    return ret;
}

std::string AccountTransferStandingInstructionsHistory::toString() const
{
    return toJson().toStyledString();
}

Json::Value AccountTransferStandingInstructionsHistory::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getBusinessId())
            {
                ret[pMasqueradingVector[1]]=getValueOfBusinessId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getStandingInstructionId())
            {
                ret[pMasqueradingVector[2]]=getValueOfStandingInstructionId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[3]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getExecutionTime())
            {
                ret[pMasqueradingVector[4]]=getExecutionTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAmount())
            {
                ret[pMasqueradingVector[5]]=getValueOfAmount();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getErrorLog())
            {
                ret[pMasqueradingVector[6]]=getValueOfErrorLog();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusinessId())
    {
        ret["business_id"]=getValueOfBusinessId();
    }
    else
    {
        ret["business_id"]=Json::Value();
    }
    if(getStandingInstructionId())
    {
        ret["standing_instruction_id"]=getValueOfStandingInstructionId();
    }
    else
    {
        ret["standing_instruction_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getExecutionTime())
    {
        ret["execution_time"]=getExecutionTime()->toDbStringLocal();
    }
    else
    {
        ret["execution_time"]=Json::Value();
    }
    if(getAmount())
    {
        ret["amount"]=getValueOfAmount();
    }
    else
    {
        ret["amount"]=Json::Value();
    }
    if(getErrorLog())
    {
        ret["error_log"]=getValueOfErrorLog();
    }
    else
    {
        ret["error_log"]=Json::Value();
    }
    return ret;
}

bool AccountTransferStandingInstructionsHistory::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("business_id"))
    {
        if(!validJsonOfField(1, "business_id", pJson["business_id"], err, true))
            return false;
    }
    if(pJson.isMember("standing_instruction_id"))
    {
        if(!validJsonOfField(2, "standing_instruction_id", pJson["standing_instruction_id"], err, true))
            return false;
    }
    else
    {
        err="The standing_instruction_id column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(3, "status", pJson["status"], err, true))
            return false;
    }
    else
    {
        err="The status column cannot be null";
        return false;
    }
    if(pJson.isMember("execution_time"))
    {
        if(!validJsonOfField(4, "execution_time", pJson["execution_time"], err, true))
            return false;
    }
    if(pJson.isMember("amount"))
    {
        if(!validJsonOfField(5, "amount", pJson["amount"], err, true))
            return false;
    }
    else
    {
        err="The amount column cannot be null";
        return false;
    }
    if(pJson.isMember("error_log"))
    {
        if(!validJsonOfField(6, "error_log", pJson["error_log"], err, true))
            return false;
    }
    return true;
}
bool AccountTransferStandingInstructionsHistory::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                                    const std::vector<std::string> &pMasqueradingVector,
                                                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AccountTransferStandingInstructionsHistory::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("business_id"))
    {
        if(!validJsonOfField(1, "business_id", pJson["business_id"], err, false))
            return false;
    }
    if(pJson.isMember("standing_instruction_id"))
    {
        if(!validJsonOfField(2, "standing_instruction_id", pJson["standing_instruction_id"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(3, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("execution_time"))
    {
        if(!validJsonOfField(4, "execution_time", pJson["execution_time"], err, false))
            return false;
    }
    if(pJson.isMember("amount"))
    {
        if(!validJsonOfField(5, "amount", pJson["amount"], err, false))
            return false;
    }
    if(pJson.isMember("error_log"))
    {
        if(!validJsonOfField(6, "error_log", pJson["error_log"], err, false))
            return false;
    }
    return true;
}
bool AccountTransferStandingInstructionsHistory::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                                                  const std::vector<std::string> &pMasqueradingVector,
                                                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AccountTransferStandingInstructionsHistory::validJsonOfField(size_t index,
                                                                  const std::string &fieldName,
                                                                  const Json::Value &pJson,
                                                                  std::string &err,
                                                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 500)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 500)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
