/**
 *
 *  Client.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace TlCustomerDb
{

class Client
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _account_no;
        static const std::string _external_id;
        static const std::string _status_enum;
        static const std::string _sub_status;
        static const std::string _activation_date;
        static const std::string _office_joining_date;
        static const std::string _office_id;
        static const std::string _transfer_to_office_id;
        static const std::string _staff_id;
        static const std::string _firstname;
        static const std::string _middlename;
        static const std::string _lastname;
        static const std::string _fullname;
        static const std::string _display_name;
        static const std::string _mobile_no;
        static const std::string _is_staff;
        static const std::string _gender_cv_id;
        static const std::string _date_of_birth;
        static const std::string _image_id;
        static const std::string _closure_reason_cv_id;
        static const std::string _closedon_date;
        static const std::string _updated_by;
        static const std::string _updated_on;
        static const std::string _submittedon_date;
        static const std::string _activatedon_userid;
        static const std::string _closedon_userid;
        static const std::string _default_savings_product;
        static const std::string _default_savings_account;
        static const std::string _client_type_cv_id;
        static const std::string _client_classification_cv_id;
        static const std::string _reject_reason_cv_id;
        static const std::string _rejectedon_date;
        static const std::string _rejectedon_userid;
        static const std::string _withdraw_reason_cv_id;
        static const std::string _withdrawn_on_date;
        static const std::string _withdraw_on_userid;
        static const std::string _reactivated_on_date;
        static const std::string _reactivated_on_userid;
        static const std::string _legal_form_enum;
        static const std::string _reopened_on_date;
        static const std::string _reopened_by_userid;
        static const std::string _email_address;
        static const std::string _proposed_transfer_date;
        static const std::string _created_on_utc;
        static const std::string _created_by;
        static const std::string _last_modified_by;
        static const std::string _last_modified_on_utc;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Client(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Client(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Client(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Client() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column account_no  */
    ///Get the value of the column account_no, returns the default value if the column is null
    const std::string &getValueOfAccountNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAccountNo() const noexcept;
    ///Set the value of the column account_no
    void setAccountNo(const std::string &pAccountNo) noexcept;
    void setAccountNo(std::string &&pAccountNo) noexcept;

    /**  For column external_id  */
    ///Get the value of the column external_id, returns the default value if the column is null
    const std::string &getValueOfExternalId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getExternalId() const noexcept;
    ///Set the value of the column external_id
    void setExternalId(const std::string &pExternalId) noexcept;
    void setExternalId(std::string &&pExternalId) noexcept;
    void setExternalIdToNull() noexcept;

    /**  For column status_enum  */
    ///Get the value of the column status_enum, returns the default value if the column is null
    const int32_t &getValueOfStatusEnum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getStatusEnum() const noexcept;
    ///Set the value of the column status_enum
    void setStatusEnum(const int32_t &pStatusEnum) noexcept;

    /**  For column sub_status  */
    ///Get the value of the column sub_status, returns the default value if the column is null
    const int32_t &getValueOfSubStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSubStatus() const noexcept;
    ///Set the value of the column sub_status
    void setSubStatus(const int32_t &pSubStatus) noexcept;
    void setSubStatusToNull() noexcept;

    /**  For column activation_date  */
    ///Get the value of the column activation_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfActivationDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getActivationDate() const noexcept;
    ///Set the value of the column activation_date
    void setActivationDate(const ::trantor::Date &pActivationDate) noexcept;
    void setActivationDateToNull() noexcept;

    /**  For column office_joining_date  */
    ///Get the value of the column office_joining_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfOfficeJoiningDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getOfficeJoiningDate() const noexcept;
    ///Set the value of the column office_joining_date
    void setOfficeJoiningDate(const ::trantor::Date &pOfficeJoiningDate) noexcept;
    void setOfficeJoiningDateToNull() noexcept;

    /**  For column office_id  */
    ///Get the value of the column office_id, returns the default value if the column is null
    const std::string &getValueOfOfficeId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getOfficeId() const noexcept;
    ///Set the value of the column office_id
    void setOfficeId(const std::string &pOfficeId) noexcept;
    void setOfficeId(std::string &&pOfficeId) noexcept;

    /**  For column transfer_to_office_id  */
    ///Get the value of the column transfer_to_office_id, returns the default value if the column is null
    const std::string &getValueOfTransferToOfficeId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTransferToOfficeId() const noexcept;
    ///Set the value of the column transfer_to_office_id
    void setTransferToOfficeId(const std::string &pTransferToOfficeId) noexcept;
    void setTransferToOfficeId(std::string &&pTransferToOfficeId) noexcept;

    /**  For column staff_id  */
    ///Get the value of the column staff_id, returns the default value if the column is null
    const std::string &getValueOfStaffId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStaffId() const noexcept;
    ///Set the value of the column staff_id
    void setStaffId(const std::string &pStaffId) noexcept;
    void setStaffId(std::string &&pStaffId) noexcept;

    /**  For column firstname  */
    ///Get the value of the column firstname, returns the default value if the column is null
    const std::string &getValueOfFirstname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFirstname() const noexcept;
    ///Set the value of the column firstname
    void setFirstname(const std::string &pFirstname) noexcept;
    void setFirstname(std::string &&pFirstname) noexcept;
    void setFirstnameToNull() noexcept;

    /**  For column middlename  */
    ///Get the value of the column middlename, returns the default value if the column is null
    const std::string &getValueOfMiddlename() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMiddlename() const noexcept;
    ///Set the value of the column middlename
    void setMiddlename(const std::string &pMiddlename) noexcept;
    void setMiddlename(std::string &&pMiddlename) noexcept;
    void setMiddlenameToNull() noexcept;

    /**  For column lastname  */
    ///Get the value of the column lastname, returns the default value if the column is null
    const std::string &getValueOfLastname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLastname() const noexcept;
    ///Set the value of the column lastname
    void setLastname(const std::string &pLastname) noexcept;
    void setLastname(std::string &&pLastname) noexcept;
    void setLastnameToNull() noexcept;

    /**  For column fullname  */
    ///Get the value of the column fullname, returns the default value if the column is null
    const std::string &getValueOfFullname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFullname() const noexcept;
    ///Set the value of the column fullname
    void setFullname(const std::string &pFullname) noexcept;
    void setFullname(std::string &&pFullname) noexcept;
    void setFullnameToNull() noexcept;

    /**  For column display_name  */
    ///Get the value of the column display_name, returns the default value if the column is null
    const std::string &getValueOfDisplayName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDisplayName() const noexcept;
    ///Set the value of the column display_name
    void setDisplayName(const std::string &pDisplayName) noexcept;
    void setDisplayName(std::string &&pDisplayName) noexcept;
    void setDisplayNameToNull() noexcept;

    /**  For column mobile_no  */
    ///Get the value of the column mobile_no, returns the default value if the column is null
    const std::string &getValueOfMobileNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMobileNo() const noexcept;
    ///Set the value of the column mobile_no
    void setMobileNo(const std::string &pMobileNo) noexcept;
    void setMobileNo(std::string &&pMobileNo) noexcept;
    void setMobileNoToNull() noexcept;

    /**  For column is_staff  */
    ///Get the value of the column is_staff, returns the default value if the column is null
    const bool &getValueOfIsStaff() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsStaff() const noexcept;
    ///Set the value of the column is_staff
    void setIsStaff(const bool &pIsStaff) noexcept;

    /**  For column gender_cv_id  */
    ///Get the value of the column gender_cv_id, returns the default value if the column is null
    const std::string &getValueOfGenderCvId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGenderCvId() const noexcept;
    ///Set the value of the column gender_cv_id
    void setGenderCvId(const std::string &pGenderCvId) noexcept;
    void setGenderCvId(std::string &&pGenderCvId) noexcept;

    /**  For column date_of_birth  */
    ///Get the value of the column date_of_birth, returns the default value if the column is null
    const ::trantor::Date &getValueOfDateOfBirth() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDateOfBirth() const noexcept;
    ///Set the value of the column date_of_birth
    void setDateOfBirth(const ::trantor::Date &pDateOfBirth) noexcept;
    void setDateOfBirthToNull() noexcept;

    /**  For column image_id  */
    ///Get the value of the column image_id, returns the default value if the column is null
    const std::string &getValueOfImageId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getImageId() const noexcept;
    ///Set the value of the column image_id
    void setImageId(const std::string &pImageId) noexcept;
    void setImageId(std::string &&pImageId) noexcept;

    /**  For column closure_reason_cv_id  */
    ///Get the value of the column closure_reason_cv_id, returns the default value if the column is null
    const std::string &getValueOfClosureReasonCvId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClosureReasonCvId() const noexcept;
    ///Set the value of the column closure_reason_cv_id
    void setClosureReasonCvId(const std::string &pClosureReasonCvId) noexcept;
    void setClosureReasonCvId(std::string &&pClosureReasonCvId) noexcept;

    /**  For column closedon_date  */
    ///Get the value of the column closedon_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfClosedonDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getClosedonDate() const noexcept;
    ///Set the value of the column closedon_date
    void setClosedonDate(const ::trantor::Date &pClosedonDate) noexcept;
    void setClosedonDateToNull() noexcept;

    /**  For column updated_by  */
    ///Get the value of the column updated_by, returns the default value if the column is null
    const std::string &getValueOfUpdatedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUpdatedBy() const noexcept;
    ///Set the value of the column updated_by
    void setUpdatedBy(const std::string &pUpdatedBy) noexcept;
    void setUpdatedBy(std::string &&pUpdatedBy) noexcept;

    /**  For column updated_on  */
    ///Get the value of the column updated_on, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedOn() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedOn() const noexcept;
    ///Set the value of the column updated_on
    void setUpdatedOn(const ::trantor::Date &pUpdatedOn) noexcept;
    void setUpdatedOnToNull() noexcept;

    /**  For column submittedon_date  */
    ///Get the value of the column submittedon_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfSubmittedonDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getSubmittedonDate() const noexcept;
    ///Set the value of the column submittedon_date
    void setSubmittedonDate(const ::trantor::Date &pSubmittedonDate) noexcept;
    void setSubmittedonDateToNull() noexcept;

    /**  For column activatedon_userid  */
    ///Get the value of the column activatedon_userid, returns the default value if the column is null
    const std::string &getValueOfActivatedonUserid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getActivatedonUserid() const noexcept;
    ///Set the value of the column activatedon_userid
    void setActivatedonUserid(const std::string &pActivatedonUserid) noexcept;
    void setActivatedonUserid(std::string &&pActivatedonUserid) noexcept;

    /**  For column closedon_userid  */
    ///Get the value of the column closedon_userid, returns the default value if the column is null
    const std::string &getValueOfClosedonUserid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClosedonUserid() const noexcept;
    ///Set the value of the column closedon_userid
    void setClosedonUserid(const std::string &pClosedonUserid) noexcept;
    void setClosedonUserid(std::string &&pClosedonUserid) noexcept;

    /**  For column default_savings_product  */
    ///Get the value of the column default_savings_product, returns the default value if the column is null
    const std::string &getValueOfDefaultSavingsProduct() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDefaultSavingsProduct() const noexcept;
    ///Set the value of the column default_savings_product
    void setDefaultSavingsProduct(const std::string &pDefaultSavingsProduct) noexcept;
    void setDefaultSavingsProduct(std::string &&pDefaultSavingsProduct) noexcept;

    /**  For column default_savings_account  */
    ///Get the value of the column default_savings_account, returns the default value if the column is null
    const std::string &getValueOfDefaultSavingsAccount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDefaultSavingsAccount() const noexcept;
    ///Set the value of the column default_savings_account
    void setDefaultSavingsAccount(const std::string &pDefaultSavingsAccount) noexcept;
    void setDefaultSavingsAccount(std::string &&pDefaultSavingsAccount) noexcept;

    /**  For column client_type_cv_id  */
    ///Get the value of the column client_type_cv_id, returns the default value if the column is null
    const std::string &getValueOfClientTypeCvId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientTypeCvId() const noexcept;
    ///Set the value of the column client_type_cv_id
    void setClientTypeCvId(const std::string &pClientTypeCvId) noexcept;
    void setClientTypeCvId(std::string &&pClientTypeCvId) noexcept;

    /**  For column client_classification_cv_id  */
    ///Get the value of the column client_classification_cv_id, returns the default value if the column is null
    const std::string &getValueOfClientClassificationCvId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientClassificationCvId() const noexcept;
    ///Set the value of the column client_classification_cv_id
    void setClientClassificationCvId(const std::string &pClientClassificationCvId) noexcept;
    void setClientClassificationCvId(std::string &&pClientClassificationCvId) noexcept;

    /**  For column reject_reason_cv_id  */
    ///Get the value of the column reject_reason_cv_id, returns the default value if the column is null
    const std::string &getValueOfRejectReasonCvId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRejectReasonCvId() const noexcept;
    ///Set the value of the column reject_reason_cv_id
    void setRejectReasonCvId(const std::string &pRejectReasonCvId) noexcept;
    void setRejectReasonCvId(std::string &&pRejectReasonCvId) noexcept;

    /**  For column rejectedon_date  */
    ///Get the value of the column rejectedon_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfRejectedonDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getRejectedonDate() const noexcept;
    ///Set the value of the column rejectedon_date
    void setRejectedonDate(const ::trantor::Date &pRejectedonDate) noexcept;
    void setRejectedonDateToNull() noexcept;

    /**  For column rejectedon_userid  */
    ///Get the value of the column rejectedon_userid, returns the default value if the column is null
    const std::string &getValueOfRejectedonUserid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRejectedonUserid() const noexcept;
    ///Set the value of the column rejectedon_userid
    void setRejectedonUserid(const std::string &pRejectedonUserid) noexcept;
    void setRejectedonUserid(std::string &&pRejectedonUserid) noexcept;

    /**  For column withdraw_reason_cv_id  */
    ///Get the value of the column withdraw_reason_cv_id, returns the default value if the column is null
    const std::string &getValueOfWithdrawReasonCvId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWithdrawReasonCvId() const noexcept;
    ///Set the value of the column withdraw_reason_cv_id
    void setWithdrawReasonCvId(const std::string &pWithdrawReasonCvId) noexcept;
    void setWithdrawReasonCvId(std::string &&pWithdrawReasonCvId) noexcept;

    /**  For column withdrawn_on_date  */
    ///Get the value of the column withdrawn_on_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfWithdrawnOnDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getWithdrawnOnDate() const noexcept;
    ///Set the value of the column withdrawn_on_date
    void setWithdrawnOnDate(const ::trantor::Date &pWithdrawnOnDate) noexcept;
    void setWithdrawnOnDateToNull() noexcept;

    /**  For column withdraw_on_userid  */
    ///Get the value of the column withdraw_on_userid, returns the default value if the column is null
    const std::string &getValueOfWithdrawOnUserid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWithdrawOnUserid() const noexcept;
    ///Set the value of the column withdraw_on_userid
    void setWithdrawOnUserid(const std::string &pWithdrawOnUserid) noexcept;
    void setWithdrawOnUserid(std::string &&pWithdrawOnUserid) noexcept;

    /**  For column reactivated_on_date  */
    ///Get the value of the column reactivated_on_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfReactivatedOnDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getReactivatedOnDate() const noexcept;
    ///Set the value of the column reactivated_on_date
    void setReactivatedOnDate(const ::trantor::Date &pReactivatedOnDate) noexcept;
    void setReactivatedOnDateToNull() noexcept;

    /**  For column reactivated_on_userid  */
    ///Get the value of the column reactivated_on_userid, returns the default value if the column is null
    const std::string &getValueOfReactivatedOnUserid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReactivatedOnUserid() const noexcept;
    ///Set the value of the column reactivated_on_userid
    void setReactivatedOnUserid(const std::string &pReactivatedOnUserid) noexcept;
    void setReactivatedOnUserid(std::string &&pReactivatedOnUserid) noexcept;

    /**  For column legal_form_enum  */
    ///Get the value of the column legal_form_enum, returns the default value if the column is null
    const int32_t &getValueOfLegalFormEnum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getLegalFormEnum() const noexcept;
    ///Set the value of the column legal_form_enum
    void setLegalFormEnum(const int32_t &pLegalFormEnum) noexcept;
    void setLegalFormEnumToNull() noexcept;

    /**  For column reopened_on_date  */
    ///Get the value of the column reopened_on_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfReopenedOnDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getReopenedOnDate() const noexcept;
    ///Set the value of the column reopened_on_date
    void setReopenedOnDate(const ::trantor::Date &pReopenedOnDate) noexcept;
    void setReopenedOnDateToNull() noexcept;

    /**  For column reopened_by_userid  */
    ///Get the value of the column reopened_by_userid, returns the default value if the column is null
    const std::string &getValueOfReopenedByUserid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReopenedByUserid() const noexcept;
    ///Set the value of the column reopened_by_userid
    void setReopenedByUserid(const std::string &pReopenedByUserid) noexcept;
    void setReopenedByUserid(std::string &&pReopenedByUserid) noexcept;

    /**  For column email_address  */
    ///Get the value of the column email_address, returns the default value if the column is null
    const std::string &getValueOfEmailAddress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEmailAddress() const noexcept;
    ///Set the value of the column email_address
    void setEmailAddress(const std::string &pEmailAddress) noexcept;
    void setEmailAddress(std::string &&pEmailAddress) noexcept;
    void setEmailAddressToNull() noexcept;

    /**  For column proposed_transfer_date  */
    ///Get the value of the column proposed_transfer_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfProposedTransferDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getProposedTransferDate() const noexcept;
    ///Set the value of the column proposed_transfer_date
    void setProposedTransferDate(const ::trantor::Date &pProposedTransferDate) noexcept;
    void setProposedTransferDateToNull() noexcept;

    /**  For column created_on_utc  */
    ///Get the value of the column created_on_utc, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedOnUtc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedOnUtc() const noexcept;
    ///Set the value of the column created_on_utc
    void setCreatedOnUtc(const ::trantor::Date &pCreatedOnUtc) noexcept;
    void setCreatedOnUtcToNull() noexcept;

    /**  For column created_by  */
    ///Get the value of the column created_by, returns the default value if the column is null
    const std::string &getValueOfCreatedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCreatedBy() const noexcept;
    ///Set the value of the column created_by
    void setCreatedBy(const std::string &pCreatedBy) noexcept;
    void setCreatedBy(std::string &&pCreatedBy) noexcept;

    /**  For column last_modified_by  */
    ///Get the value of the column last_modified_by, returns the default value if the column is null
    const std::string &getValueOfLastModifiedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLastModifiedBy() const noexcept;
    ///Set the value of the column last_modified_by
    void setLastModifiedBy(const std::string &pLastModifiedBy) noexcept;
    void setLastModifiedBy(std::string &&pLastModifiedBy) noexcept;

    /**  For column last_modified_on_utc  */
    ///Get the value of the column last_modified_on_utc, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastModifiedOnUtc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastModifiedOnUtc() const noexcept;
    ///Set the value of the column last_modified_on_utc
    void setLastModifiedOnUtc(const ::trantor::Date &pLastModifiedOnUtc) noexcept;
    void setLastModifiedOnUtcToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 48;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Client>;
    friend drogon::orm::BaseBuilder<Client, true, true>;
    friend drogon::orm::BaseBuilder<Client, true, false>;
    friend drogon::orm::BaseBuilder<Client, false, true>;
    friend drogon::orm::BaseBuilder<Client, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Client>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> accountNo_;
    std::shared_ptr<std::string> externalId_;
    std::shared_ptr<int32_t> statusEnum_;
    std::shared_ptr<int32_t> subStatus_;
    std::shared_ptr<::trantor::Date> activationDate_;
    std::shared_ptr<::trantor::Date> officeJoiningDate_;
    std::shared_ptr<std::string> officeId_;
    std::shared_ptr<std::string> transferToOfficeId_;
    std::shared_ptr<std::string> staffId_;
    std::shared_ptr<std::string> firstname_;
    std::shared_ptr<std::string> middlename_;
    std::shared_ptr<std::string> lastname_;
    std::shared_ptr<std::string> fullname_;
    std::shared_ptr<std::string> displayName_;
    std::shared_ptr<std::string> mobileNo_;
    std::shared_ptr<bool> isStaff_;
    std::shared_ptr<std::string> genderCvId_;
    std::shared_ptr<::trantor::Date> dateOfBirth_;
    std::shared_ptr<std::string> imageId_;
    std::shared_ptr<std::string> closureReasonCvId_;
    std::shared_ptr<::trantor::Date> closedonDate_;
    std::shared_ptr<std::string> updatedBy_;
    std::shared_ptr<::trantor::Date> updatedOn_;
    std::shared_ptr<::trantor::Date> submittedonDate_;
    std::shared_ptr<std::string> activatedonUserid_;
    std::shared_ptr<std::string> closedonUserid_;
    std::shared_ptr<std::string> defaultSavingsProduct_;
    std::shared_ptr<std::string> defaultSavingsAccount_;
    std::shared_ptr<std::string> clientTypeCvId_;
    std::shared_ptr<std::string> clientClassificationCvId_;
    std::shared_ptr<std::string> rejectReasonCvId_;
    std::shared_ptr<::trantor::Date> rejectedonDate_;
    std::shared_ptr<std::string> rejectedonUserid_;
    std::shared_ptr<std::string> withdrawReasonCvId_;
    std::shared_ptr<::trantor::Date> withdrawnOnDate_;
    std::shared_ptr<std::string> withdrawOnUserid_;
    std::shared_ptr<::trantor::Date> reactivatedOnDate_;
    std::shared_ptr<std::string> reactivatedOnUserid_;
    std::shared_ptr<int32_t> legalFormEnum_;
    std::shared_ptr<::trantor::Date> reopenedOnDate_;
    std::shared_ptr<std::string> reopenedByUserid_;
    std::shared_ptr<std::string> emailAddress_;
    std::shared_ptr<::trantor::Date> proposedTransferDate_;
    std::shared_ptr<::trantor::Date> createdOnUtc_;
    std::shared_ptr<std::string> createdBy_;
    std::shared_ptr<std::string> lastModifiedBy_;
    std::shared_ptr<::trantor::Date> lastModifiedOnUtc_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[48]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "account_no,";
            ++parametersCount;
        }
        sql += "external_id,";
        ++parametersCount;
        if(!dirtyFlag_[2])
        {
            needSelection=true;
        }
        sql += "status_enum,";
        ++parametersCount;
        if(!dirtyFlag_[3])
        {
            needSelection=true;
        }
        if(dirtyFlag_[4])
        {
            sql += "sub_status,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "activation_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "office_joining_date,";
            ++parametersCount;
        }
        sql += "office_id,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        sql += "transfer_to_office_id,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        sql += "staff_id,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        sql += "firstname,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        sql += "middlename,";
        ++parametersCount;
        if(!dirtyFlag_[11])
        {
            needSelection=true;
        }
        sql += "lastname,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        sql += "fullname,";
        ++parametersCount;
        if(!dirtyFlag_[13])
        {
            needSelection=true;
        }
        sql += "display_name,";
        ++parametersCount;
        if(!dirtyFlag_[14])
        {
            needSelection=true;
        }
        sql += "mobile_no,";
        ++parametersCount;
        if(!dirtyFlag_[15])
        {
            needSelection=true;
        }
        sql += "is_staff,";
        ++parametersCount;
        if(!dirtyFlag_[16])
        {
            needSelection=true;
        }
        sql += "gender_cv_id,";
        ++parametersCount;
        if(!dirtyFlag_[17])
        {
            needSelection=true;
        }
        if(dirtyFlag_[18])
        {
            sql += "date_of_birth,";
            ++parametersCount;
        }
        sql += "image_id,";
        ++parametersCount;
        if(!dirtyFlag_[19])
        {
            needSelection=true;
        }
        sql += "closure_reason_cv_id,";
        ++parametersCount;
        if(!dirtyFlag_[20])
        {
            needSelection=true;
        }
        if(dirtyFlag_[21])
        {
            sql += "closedon_date,";
            ++parametersCount;
        }
        sql += "updated_by,";
        ++parametersCount;
        if(!dirtyFlag_[22])
        {
            needSelection=true;
        }
        if(dirtyFlag_[23])
        {
            sql += "updated_on,";
            ++parametersCount;
        }
        if(dirtyFlag_[24])
        {
            sql += "submittedon_date,";
            ++parametersCount;
        }
        sql += "activatedon_userid,";
        ++parametersCount;
        if(!dirtyFlag_[25])
        {
            needSelection=true;
        }
        sql += "closedon_userid,";
        ++parametersCount;
        if(!dirtyFlag_[26])
        {
            needSelection=true;
        }
        if(dirtyFlag_[27])
        {
            sql += "default_savings_product,";
            ++parametersCount;
        }
        if(dirtyFlag_[28])
        {
            sql += "default_savings_account,";
            ++parametersCount;
        }
        sql += "client_type_cv_id,";
        ++parametersCount;
        if(!dirtyFlag_[29])
        {
            needSelection=true;
        }
        sql += "client_classification_cv_id,";
        ++parametersCount;
        if(!dirtyFlag_[30])
        {
            needSelection=true;
        }
        sql += "reject_reason_cv_id,";
        ++parametersCount;
        if(!dirtyFlag_[31])
        {
            needSelection=true;
        }
        if(dirtyFlag_[32])
        {
            sql += "rejectedon_date,";
            ++parametersCount;
        }
        sql += "rejectedon_userid,";
        ++parametersCount;
        if(!dirtyFlag_[33])
        {
            needSelection=true;
        }
        sql += "withdraw_reason_cv_id,";
        ++parametersCount;
        if(!dirtyFlag_[34])
        {
            needSelection=true;
        }
        if(dirtyFlag_[35])
        {
            sql += "withdrawn_on_date,";
            ++parametersCount;
        }
        sql += "withdraw_on_userid,";
        ++parametersCount;
        if(!dirtyFlag_[36])
        {
            needSelection=true;
        }
        if(dirtyFlag_[37])
        {
            sql += "reactivated_on_date,";
            ++parametersCount;
        }
        sql += "reactivated_on_userid,";
        ++parametersCount;
        if(!dirtyFlag_[38])
        {
            needSelection=true;
        }
        if(dirtyFlag_[39])
        {
            sql += "legal_form_enum,";
            ++parametersCount;
        }
        if(dirtyFlag_[40])
        {
            sql += "reopened_on_date,";
            ++parametersCount;
        }
        sql += "reopened_by_userid,";
        ++parametersCount;
        if(!dirtyFlag_[41])
        {
            needSelection=true;
        }
        sql += "email_address,";
        ++parametersCount;
        if(!dirtyFlag_[42])
        {
            needSelection=true;
        }
        if(dirtyFlag_[43])
        {
            sql += "proposed_transfer_date,";
            ++parametersCount;
        }
        sql += "created_on_utc,";
        ++parametersCount;
        if(!dirtyFlag_[44])
        {
            needSelection=true;
        }
        sql += "created_by,";
        ++parametersCount;
        if(!dirtyFlag_[45])
        {
            needSelection=true;
        }
        sql += "last_modified_by,";
        ++parametersCount;
        if(!dirtyFlag_[46])
        {
            needSelection=true;
        }
        sql += "last_modified_on_utc,";
        ++parametersCount;
        if(!dirtyFlag_[47])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[15])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[16])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[17])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[18])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[19])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[20])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[21])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[22])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[23])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[24])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[25])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[26])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[27])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[28])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[29])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[30])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[31])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[32])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[33])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[34])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[35])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[36])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[37])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[38])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[39])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[40])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[41])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[42])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[43])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[44])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[45])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[46])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[47])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace TlCustomerDb
} // namespace drogon_model
