/**
 *
 *  ClientTransaction.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ClientTransaction.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::TlCustomerDb;

const std::string ClientTransaction::Cols::_id = "\"id\"";
const std::string ClientTransaction::Cols::_client_id = "\"client_id\"";
const std::string ClientTransaction::Cols::_office_id = "\"office_id\"";
const std::string ClientTransaction::Cols::_currency_code = "\"currency_code\"";
const std::string ClientTransaction::Cols::_payment_detail_id = "\"payment_detail_id\"";
const std::string ClientTransaction::Cols::_is_reversed = "\"is_reversed\"";
const std::string ClientTransaction::Cols::_external_id = "\"external_id\"";
const std::string ClientTransaction::Cols::_transaction_date = "\"transaction_date\"";
const std::string ClientTransaction::Cols::_transaction_type_enum = "\"transaction_type_enum\"";
const std::string ClientTransaction::Cols::_amount = "\"amount\"";
const std::string ClientTransaction::Cols::_created_date = "\"created_date\"";
const std::string ClientTransaction::Cols::_created_on_utc = "\"created_on_utc\"";
const std::string ClientTransaction::Cols::_created_by = "\"created_by\"";
const std::string ClientTransaction::Cols::_last_modified_by = "\"last_modified_by\"";
const std::string ClientTransaction::Cols::_last_modified_on_utc = "\"last_modified_on_utc\"";
const std::string ClientTransaction::Cols::_submitted_on_date = "\"submitted_on_date\"";
const std::string ClientTransaction::primaryKeyName = "id";
const bool ClientTransaction::hasPrimaryKey = true;
const std::string ClientTransaction::tableName = "\"client_transaction\"";

const std::vector<typename ClientTransaction::MetaData> ClientTransaction::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"client_id","std::string","uuid",0,0,0,1},
{"office_id","std::string","uuid",0,0,0,1},
{"currency_code","std::string","character varying",20,0,0,1},
{"payment_detail_id","std::string","uuid",0,0,0,0},
{"is_reversed","bool","boolean",1,0,0,1},
{"external_id","std::string","character varying",50,0,0,0},
{"transaction_date","::trantor::Date","date",0,0,0,1},
{"transaction_type_enum","int32_t","integer",4,0,0,1},
{"amount","std::string","numeric",0,0,0,1},
{"created_date","::trantor::Date","timestamp without time zone",0,0,0,0},
{"created_on_utc","::trantor::Date","timestamp without time zone",0,0,0,0},
{"created_by","std::string","uuid",0,0,0,1},
{"last_modified_by","std::string","uuid",0,0,0,1},
{"last_modified_on_utc","::trantor::Date","timestamp without time zone",0,0,0,0},
{"submitted_on_date","::trantor::Date","date",0,0,0,1}
};
const std::string &ClientTransaction::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ClientTransaction::ClientTransaction(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(r["client_id"].as<std::string>());
        }
        if(!r["office_id"].isNull())
        {
            officeId_=std::make_shared<std::string>(r["office_id"].as<std::string>());
        }
        if(!r["currency_code"].isNull())
        {
            currencyCode_=std::make_shared<std::string>(r["currency_code"].as<std::string>());
        }
        if(!r["payment_detail_id"].isNull())
        {
            paymentDetailId_=std::make_shared<std::string>(r["payment_detail_id"].as<std::string>());
        }
        if(!r["is_reversed"].isNull())
        {
            isReversed_=std::make_shared<bool>(r["is_reversed"].as<bool>());
        }
        if(!r["external_id"].isNull())
        {
            externalId_=std::make_shared<std::string>(r["external_id"].as<std::string>());
        }
        if(!r["transaction_date"].isNull())
        {
            auto daysStr = r["transaction_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            transactionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["transaction_type_enum"].isNull())
        {
            transactionTypeEnum_=std::make_shared<int32_t>(r["transaction_type_enum"].as<int32_t>());
        }
        if(!r["amount"].isNull())
        {
            amount_=std::make_shared<std::string>(r["amount"].as<std::string>());
        }
        if(!r["created_date"].isNull())
        {
            auto timeStr = r["created_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["created_on_utc"].isNull())
        {
            auto timeStr = r["created_on_utc"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(r["created_by"].as<std::string>());
        }
        if(!r["last_modified_by"].isNull())
        {
            lastModifiedBy_=std::make_shared<std::string>(r["last_modified_by"].as<std::string>());
        }
        if(!r["last_modified_on_utc"].isNull())
        {
            auto timeStr = r["last_modified_on_utc"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastModifiedOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["submitted_on_date"].isNull())
        {
            auto daysStr = r["submitted_on_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submittedOnDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 16 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            clientId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            officeId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            currencyCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            paymentDetailId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            isReversed_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            externalId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            transactionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            transactionTypeEnum_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            amount_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            createdBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            lastModifiedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastModifiedOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 15;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submittedOnDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }

}

ClientTransaction::ClientTransaction(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 16)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            officeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            currencyCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            paymentDetailId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            isReversed_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            transactionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            transactionTypeEnum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            amount_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            lastModifiedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[14]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastModifiedOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submittedOnDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

ClientTransaction::ClientTransaction(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("office_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["office_id"].isNull())
        {
            officeId_=std::make_shared<std::string>(pJson["office_id"].asString());
        }
    }
    if(pJson.isMember("currency_code"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["currency_code"].isNull())
        {
            currencyCode_=std::make_shared<std::string>(pJson["currency_code"].asString());
        }
    }
    if(pJson.isMember("payment_detail_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["payment_detail_id"].isNull())
        {
            paymentDetailId_=std::make_shared<std::string>(pJson["payment_detail_id"].asString());
        }
    }
    if(pJson.isMember("is_reversed"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["is_reversed"].isNull())
        {
            isReversed_=std::make_shared<bool>(pJson["is_reversed"].asBool());
        }
    }
    if(pJson.isMember("external_id"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["external_id"].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson["external_id"].asString());
        }
    }
    if(pJson.isMember("transaction_date"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["transaction_date"].isNull())
        {
            auto daysStr = pJson["transaction_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            transactionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("transaction_type_enum"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["transaction_type_enum"].isNull())
        {
            transactionTypeEnum_=std::make_shared<int32_t>((int32_t)pJson["transaction_type_enum"].asInt64());
        }
    }
    if(pJson.isMember("amount"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["amount"].isNull())
        {
            amount_=std::make_shared<std::string>(pJson["amount"].asString());
        }
    }
    if(pJson.isMember("created_date"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["created_date"].isNull())
        {
            auto timeStr = pJson["created_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_on_utc"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["created_on_utc"].isNull())
        {
            auto timeStr = pJson["created_on_utc"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson["created_by"].asString());
        }
    }
    if(pJson.isMember("last_modified_by"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["last_modified_by"].isNull())
        {
            lastModifiedBy_=std::make_shared<std::string>(pJson["last_modified_by"].asString());
        }
    }
    if(pJson.isMember("last_modified_on_utc"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["last_modified_on_utc"].isNull())
        {
            auto timeStr = pJson["last_modified_on_utc"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastModifiedOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("submitted_on_date"))
    {
        dirtyFlag_[15]=true;
        if(!pJson["submitted_on_date"].isNull())
        {
            auto daysStr = pJson["submitted_on_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submittedOnDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void ClientTransaction::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 16)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            officeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            currencyCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            paymentDetailId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            isReversed_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            transactionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            transactionTypeEnum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            amount_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            lastModifiedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[14]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastModifiedOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submittedOnDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void ClientTransaction::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("office_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["office_id"].isNull())
        {
            officeId_=std::make_shared<std::string>(pJson["office_id"].asString());
        }
    }
    if(pJson.isMember("currency_code"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["currency_code"].isNull())
        {
            currencyCode_=std::make_shared<std::string>(pJson["currency_code"].asString());
        }
    }
    if(pJson.isMember("payment_detail_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["payment_detail_id"].isNull())
        {
            paymentDetailId_=std::make_shared<std::string>(pJson["payment_detail_id"].asString());
        }
    }
    if(pJson.isMember("is_reversed"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["is_reversed"].isNull())
        {
            isReversed_=std::make_shared<bool>(pJson["is_reversed"].asBool());
        }
    }
    if(pJson.isMember("external_id"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["external_id"].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson["external_id"].asString());
        }
    }
    if(pJson.isMember("transaction_date"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["transaction_date"].isNull())
        {
            auto daysStr = pJson["transaction_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            transactionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("transaction_type_enum"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["transaction_type_enum"].isNull())
        {
            transactionTypeEnum_=std::make_shared<int32_t>((int32_t)pJson["transaction_type_enum"].asInt64());
        }
    }
    if(pJson.isMember("amount"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["amount"].isNull())
        {
            amount_=std::make_shared<std::string>(pJson["amount"].asString());
        }
    }
    if(pJson.isMember("created_date"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["created_date"].isNull())
        {
            auto timeStr = pJson["created_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_on_utc"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["created_on_utc"].isNull())
        {
            auto timeStr = pJson["created_on_utc"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson["created_by"].asString());
        }
    }
    if(pJson.isMember("last_modified_by"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["last_modified_by"].isNull())
        {
            lastModifiedBy_=std::make_shared<std::string>(pJson["last_modified_by"].asString());
        }
    }
    if(pJson.isMember("last_modified_on_utc"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["last_modified_on_utc"].isNull())
        {
            auto timeStr = pJson["last_modified_on_utc"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastModifiedOnUtc_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("submitted_on_date"))
    {
        dirtyFlag_[15] = true;
        if(!pJson["submitted_on_date"].isNull())
        {
            auto daysStr = pJson["submitted_on_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submittedOnDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

const std::string &ClientTransaction::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getId() const noexcept
{
    return id_;
}
void ClientTransaction::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void ClientTransaction::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename ClientTransaction::PrimaryKeyType & ClientTransaction::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ClientTransaction::getValueOfClientId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clientId_)
        return *clientId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getClientId() const noexcept
{
    return clientId_;
}
void ClientTransaction::setClientId(const std::string &pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(pClientId);
    dirtyFlag_[1] = true;
}
void ClientTransaction::setClientId(std::string &&pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(std::move(pClientId));
    dirtyFlag_[1] = true;
}

const std::string &ClientTransaction::getValueOfOfficeId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(officeId_)
        return *officeId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getOfficeId() const noexcept
{
    return officeId_;
}
void ClientTransaction::setOfficeId(const std::string &pOfficeId) noexcept
{
    officeId_ = std::make_shared<std::string>(pOfficeId);
    dirtyFlag_[2] = true;
}
void ClientTransaction::setOfficeId(std::string &&pOfficeId) noexcept
{
    officeId_ = std::make_shared<std::string>(std::move(pOfficeId));
    dirtyFlag_[2] = true;
}

const std::string &ClientTransaction::getValueOfCurrencyCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(currencyCode_)
        return *currencyCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getCurrencyCode() const noexcept
{
    return currencyCode_;
}
void ClientTransaction::setCurrencyCode(const std::string &pCurrencyCode) noexcept
{
    currencyCode_ = std::make_shared<std::string>(pCurrencyCode);
    dirtyFlag_[3] = true;
}
void ClientTransaction::setCurrencyCode(std::string &&pCurrencyCode) noexcept
{
    currencyCode_ = std::make_shared<std::string>(std::move(pCurrencyCode));
    dirtyFlag_[3] = true;
}

const std::string &ClientTransaction::getValueOfPaymentDetailId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(paymentDetailId_)
        return *paymentDetailId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getPaymentDetailId() const noexcept
{
    return paymentDetailId_;
}
void ClientTransaction::setPaymentDetailId(const std::string &pPaymentDetailId) noexcept
{
    paymentDetailId_ = std::make_shared<std::string>(pPaymentDetailId);
    dirtyFlag_[4] = true;
}
void ClientTransaction::setPaymentDetailId(std::string &&pPaymentDetailId) noexcept
{
    paymentDetailId_ = std::make_shared<std::string>(std::move(pPaymentDetailId));
    dirtyFlag_[4] = true;
}
void ClientTransaction::setPaymentDetailIdToNull() noexcept
{
    paymentDetailId_.reset();
    dirtyFlag_[4] = true;
}

const bool &ClientTransaction::getValueOfIsReversed() const noexcept
{
    static const bool defaultValue = bool();
    if(isReversed_)
        return *isReversed_;
    return defaultValue;
}
const std::shared_ptr<bool> &ClientTransaction::getIsReversed() const noexcept
{
    return isReversed_;
}
void ClientTransaction::setIsReversed(const bool &pIsReversed) noexcept
{
    isReversed_ = std::make_shared<bool>(pIsReversed);
    dirtyFlag_[5] = true;
}

const std::string &ClientTransaction::getValueOfExternalId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(externalId_)
        return *externalId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getExternalId() const noexcept
{
    return externalId_;
}
void ClientTransaction::setExternalId(const std::string &pExternalId) noexcept
{
    externalId_ = std::make_shared<std::string>(pExternalId);
    dirtyFlag_[6] = true;
}
void ClientTransaction::setExternalId(std::string &&pExternalId) noexcept
{
    externalId_ = std::make_shared<std::string>(std::move(pExternalId));
    dirtyFlag_[6] = true;
}
void ClientTransaction::setExternalIdToNull() noexcept
{
    externalId_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date &ClientTransaction::getValueOfTransactionDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(transactionDate_)
        return *transactionDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ClientTransaction::getTransactionDate() const noexcept
{
    return transactionDate_;
}
void ClientTransaction::setTransactionDate(const ::trantor::Date &pTransactionDate) noexcept
{
    transactionDate_ = std::make_shared<::trantor::Date>(pTransactionDate.roundDay());
    dirtyFlag_[7] = true;
}

const int32_t &ClientTransaction::getValueOfTransactionTypeEnum() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(transactionTypeEnum_)
        return *transactionTypeEnum_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ClientTransaction::getTransactionTypeEnum() const noexcept
{
    return transactionTypeEnum_;
}
void ClientTransaction::setTransactionTypeEnum(const int32_t &pTransactionTypeEnum) noexcept
{
    transactionTypeEnum_ = std::make_shared<int32_t>(pTransactionTypeEnum);
    dirtyFlag_[8] = true;
}

const std::string &ClientTransaction::getValueOfAmount() const noexcept
{
    static const std::string defaultValue = std::string();
    if(amount_)
        return *amount_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getAmount() const noexcept
{
    return amount_;
}
void ClientTransaction::setAmount(const std::string &pAmount) noexcept
{
    amount_ = std::make_shared<std::string>(pAmount);
    dirtyFlag_[9] = true;
}
void ClientTransaction::setAmount(std::string &&pAmount) noexcept
{
    amount_ = std::make_shared<std::string>(std::move(pAmount));
    dirtyFlag_[9] = true;
}

const ::trantor::Date &ClientTransaction::getValueOfCreatedDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdDate_)
        return *createdDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ClientTransaction::getCreatedDate() const noexcept
{
    return createdDate_;
}
void ClientTransaction::setCreatedDate(const ::trantor::Date &pCreatedDate) noexcept
{
    createdDate_ = std::make_shared<::trantor::Date>(pCreatedDate);
    dirtyFlag_[10] = true;
}
void ClientTransaction::setCreatedDateToNull() noexcept
{
    createdDate_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &ClientTransaction::getValueOfCreatedOnUtc() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdOnUtc_)
        return *createdOnUtc_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ClientTransaction::getCreatedOnUtc() const noexcept
{
    return createdOnUtc_;
}
void ClientTransaction::setCreatedOnUtc(const ::trantor::Date &pCreatedOnUtc) noexcept
{
    createdOnUtc_ = std::make_shared<::trantor::Date>(pCreatedOnUtc);
    dirtyFlag_[11] = true;
}
void ClientTransaction::setCreatedOnUtcToNull() noexcept
{
    createdOnUtc_.reset();
    dirtyFlag_[11] = true;
}

const std::string &ClientTransaction::getValueOfCreatedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(createdBy_)
        return *createdBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getCreatedBy() const noexcept
{
    return createdBy_;
}
void ClientTransaction::setCreatedBy(const std::string &pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<std::string>(pCreatedBy);
    dirtyFlag_[12] = true;
}
void ClientTransaction::setCreatedBy(std::string &&pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<std::string>(std::move(pCreatedBy));
    dirtyFlag_[12] = true;
}

const std::string &ClientTransaction::getValueOfLastModifiedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(lastModifiedBy_)
        return *lastModifiedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ClientTransaction::getLastModifiedBy() const noexcept
{
    return lastModifiedBy_;
}
void ClientTransaction::setLastModifiedBy(const std::string &pLastModifiedBy) noexcept
{
    lastModifiedBy_ = std::make_shared<std::string>(pLastModifiedBy);
    dirtyFlag_[13] = true;
}
void ClientTransaction::setLastModifiedBy(std::string &&pLastModifiedBy) noexcept
{
    lastModifiedBy_ = std::make_shared<std::string>(std::move(pLastModifiedBy));
    dirtyFlag_[13] = true;
}

const ::trantor::Date &ClientTransaction::getValueOfLastModifiedOnUtc() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastModifiedOnUtc_)
        return *lastModifiedOnUtc_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ClientTransaction::getLastModifiedOnUtc() const noexcept
{
    return lastModifiedOnUtc_;
}
void ClientTransaction::setLastModifiedOnUtc(const ::trantor::Date &pLastModifiedOnUtc) noexcept
{
    lastModifiedOnUtc_ = std::make_shared<::trantor::Date>(pLastModifiedOnUtc);
    dirtyFlag_[14] = true;
}
void ClientTransaction::setLastModifiedOnUtcToNull() noexcept
{
    lastModifiedOnUtc_.reset();
    dirtyFlag_[14] = true;
}

const ::trantor::Date &ClientTransaction::getValueOfSubmittedOnDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(submittedOnDate_)
        return *submittedOnDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ClientTransaction::getSubmittedOnDate() const noexcept
{
    return submittedOnDate_;
}
void ClientTransaction::setSubmittedOnDate(const ::trantor::Date &pSubmittedOnDate) noexcept
{
    submittedOnDate_ = std::make_shared<::trantor::Date>(pSubmittedOnDate.roundDay());
    dirtyFlag_[15] = true;
}

void ClientTransaction::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ClientTransaction::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "client_id",
        "office_id",
        "currency_code",
        "payment_detail_id",
        "is_reversed",
        "external_id",
        "transaction_date",
        "transaction_type_enum",
        "amount",
        "created_date",
        "created_on_utc",
        "created_by",
        "last_modified_by",
        "last_modified_on_utc",
        "submitted_on_date"
    };
    return inCols;
}

void ClientTransaction::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getOfficeId())
        {
            binder << getValueOfOfficeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCurrencyCode())
        {
            binder << getValueOfCurrencyCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPaymentDetailId())
        {
            binder << getValueOfPaymentDetailId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getIsReversed())
        {
            binder << getValueOfIsReversed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExternalId())
        {
            binder << getValueOfExternalId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTransactionDate())
        {
            binder << getValueOfTransactionDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getTransactionTypeEnum())
        {
            binder << getValueOfTransactionTypeEnum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getAmount())
        {
            binder << getValueOfAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCreatedDate())
        {
            binder << getValueOfCreatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedOnUtc())
        {
            binder << getValueOfCreatedOnUtc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getLastModifiedBy())
        {
            binder << getValueOfLastModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getLastModifiedOnUtc())
        {
            binder << getValueOfLastModifiedOnUtc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getSubmittedOnDate())
        {
            binder << getValueOfSubmittedOnDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ClientTransaction::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    if(dirtyFlag_[15])
    {
        ret.push_back(getColumnName(15));
    }
    return ret;
}

void ClientTransaction::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getOfficeId())
        {
            binder << getValueOfOfficeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCurrencyCode())
        {
            binder << getValueOfCurrencyCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPaymentDetailId())
        {
            binder << getValueOfPaymentDetailId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getIsReversed())
        {
            binder << getValueOfIsReversed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExternalId())
        {
            binder << getValueOfExternalId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTransactionDate())
        {
            binder << getValueOfTransactionDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getTransactionTypeEnum())
        {
            binder << getValueOfTransactionTypeEnum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getAmount())
        {
            binder << getValueOfAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCreatedDate())
        {
            binder << getValueOfCreatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedOnUtc())
        {
            binder << getValueOfCreatedOnUtc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getLastModifiedBy())
        {
            binder << getValueOfLastModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getLastModifiedOnUtc())
        {
            binder << getValueOfLastModifiedOnUtc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getSubmittedOnDate())
        {
            binder << getValueOfSubmittedOnDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ClientTransaction::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getOfficeId())
    {
        ret["office_id"]=getValueOfOfficeId();
    }
    else
    {
        ret["office_id"]=Json::Value();
    }
    if(getCurrencyCode())
    {
        ret["currency_code"]=getValueOfCurrencyCode();
    }
    else
    {
        ret["currency_code"]=Json::Value();
    }
    if(getPaymentDetailId())
    {
        ret["payment_detail_id"]=getValueOfPaymentDetailId();
    }
    else
    {
        ret["payment_detail_id"]=Json::Value();
    }
    if(getIsReversed())
    {
        ret["is_reversed"]=getValueOfIsReversed();
    }
    else
    {
        ret["is_reversed"]=Json::Value();
    }
    if(getExternalId())
    {
        ret["external_id"]=getValueOfExternalId();
    }
    else
    {
        ret["external_id"]=Json::Value();
    }
    if(getTransactionDate())
    {
        ret["transaction_date"]=getTransactionDate()->toDbStringLocal();
    }
    else
    {
        ret["transaction_date"]=Json::Value();
    }
    if(getTransactionTypeEnum())
    {
        ret["transaction_type_enum"]=getValueOfTransactionTypeEnum();
    }
    else
    {
        ret["transaction_type_enum"]=Json::Value();
    }
    if(getAmount())
    {
        ret["amount"]=getValueOfAmount();
    }
    else
    {
        ret["amount"]=Json::Value();
    }
    if(getCreatedDate())
    {
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    }
    else
    {
        ret["created_date"]=Json::Value();
    }
    if(getCreatedOnUtc())
    {
        ret["created_on_utc"]=getCreatedOnUtc()->toDbStringLocal();
    }
    else
    {
        ret["created_on_utc"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getLastModifiedBy())
    {
        ret["last_modified_by"]=getValueOfLastModifiedBy();
    }
    else
    {
        ret["last_modified_by"]=Json::Value();
    }
    if(getLastModifiedOnUtc())
    {
        ret["last_modified_on_utc"]=getLastModifiedOnUtc()->toDbStringLocal();
    }
    else
    {
        ret["last_modified_on_utc"]=Json::Value();
    }
    if(getSubmittedOnDate())
    {
        ret["submitted_on_date"]=getSubmittedOnDate()->toDbStringLocal();
    }
    else
    {
        ret["submitted_on_date"]=Json::Value();
    }
    return ret;
}

std::string ClientTransaction::toString() const
{
    return toJson().toStyledString();
}

Json::Value ClientTransaction::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 16)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClientId())
            {
                ret[pMasqueradingVector[1]]=getValueOfClientId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getOfficeId())
            {
                ret[pMasqueradingVector[2]]=getValueOfOfficeId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCurrencyCode())
            {
                ret[pMasqueradingVector[3]]=getValueOfCurrencyCode();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPaymentDetailId())
            {
                ret[pMasqueradingVector[4]]=getValueOfPaymentDetailId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getIsReversed())
            {
                ret[pMasqueradingVector[5]]=getValueOfIsReversed();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getExternalId())
            {
                ret[pMasqueradingVector[6]]=getValueOfExternalId();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getTransactionDate())
            {
                ret[pMasqueradingVector[7]]=getTransactionDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getTransactionTypeEnum())
            {
                ret[pMasqueradingVector[8]]=getValueOfTransactionTypeEnum();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getAmount())
            {
                ret[pMasqueradingVector[9]]=getValueOfAmount();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getCreatedDate())
            {
                ret[pMasqueradingVector[10]]=getCreatedDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getCreatedOnUtc())
            {
                ret[pMasqueradingVector[11]]=getCreatedOnUtc()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getCreatedBy())
            {
                ret[pMasqueradingVector[12]]=getValueOfCreatedBy();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getLastModifiedBy())
            {
                ret[pMasqueradingVector[13]]=getValueOfLastModifiedBy();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getLastModifiedOnUtc())
            {
                ret[pMasqueradingVector[14]]=getLastModifiedOnUtc()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[15].empty())
        {
            if(getSubmittedOnDate())
            {
                ret[pMasqueradingVector[15]]=getSubmittedOnDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[15]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getOfficeId())
    {
        ret["office_id"]=getValueOfOfficeId();
    }
    else
    {
        ret["office_id"]=Json::Value();
    }
    if(getCurrencyCode())
    {
        ret["currency_code"]=getValueOfCurrencyCode();
    }
    else
    {
        ret["currency_code"]=Json::Value();
    }
    if(getPaymentDetailId())
    {
        ret["payment_detail_id"]=getValueOfPaymentDetailId();
    }
    else
    {
        ret["payment_detail_id"]=Json::Value();
    }
    if(getIsReversed())
    {
        ret["is_reversed"]=getValueOfIsReversed();
    }
    else
    {
        ret["is_reversed"]=Json::Value();
    }
    if(getExternalId())
    {
        ret["external_id"]=getValueOfExternalId();
    }
    else
    {
        ret["external_id"]=Json::Value();
    }
    if(getTransactionDate())
    {
        ret["transaction_date"]=getTransactionDate()->toDbStringLocal();
    }
    else
    {
        ret["transaction_date"]=Json::Value();
    }
    if(getTransactionTypeEnum())
    {
        ret["transaction_type_enum"]=getValueOfTransactionTypeEnum();
    }
    else
    {
        ret["transaction_type_enum"]=Json::Value();
    }
    if(getAmount())
    {
        ret["amount"]=getValueOfAmount();
    }
    else
    {
        ret["amount"]=Json::Value();
    }
    if(getCreatedDate())
    {
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    }
    else
    {
        ret["created_date"]=Json::Value();
    }
    if(getCreatedOnUtc())
    {
        ret["created_on_utc"]=getCreatedOnUtc()->toDbStringLocal();
    }
    else
    {
        ret["created_on_utc"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getLastModifiedBy())
    {
        ret["last_modified_by"]=getValueOfLastModifiedBy();
    }
    else
    {
        ret["last_modified_by"]=Json::Value();
    }
    if(getLastModifiedOnUtc())
    {
        ret["last_modified_on_utc"]=getLastModifiedOnUtc()->toDbStringLocal();
    }
    else
    {
        ret["last_modified_on_utc"]=Json::Value();
    }
    if(getSubmittedOnDate())
    {
        ret["submitted_on_date"]=getSubmittedOnDate()->toDbStringLocal();
    }
    else
    {
        ret["submitted_on_date"]=Json::Value();
    }
    return ret;
}

bool ClientTransaction::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, true))
            return false;
    }
    else
    {
        err="The client_id column cannot be null";
        return false;
    }
    if(pJson.isMember("office_id"))
    {
        if(!validJsonOfField(2, "office_id", pJson["office_id"], err, true))
            return false;
    }
    else
    {
        err="The office_id column cannot be null";
        return false;
    }
    if(pJson.isMember("currency_code"))
    {
        if(!validJsonOfField(3, "currency_code", pJson["currency_code"], err, true))
            return false;
    }
    else
    {
        err="The currency_code column cannot be null";
        return false;
    }
    if(pJson.isMember("payment_detail_id"))
    {
        if(!validJsonOfField(4, "payment_detail_id", pJson["payment_detail_id"], err, true))
            return false;
    }
    if(pJson.isMember("is_reversed"))
    {
        if(!validJsonOfField(5, "is_reversed", pJson["is_reversed"], err, true))
            return false;
    }
    else
    {
        err="The is_reversed column cannot be null";
        return false;
    }
    if(pJson.isMember("external_id"))
    {
        if(!validJsonOfField(6, "external_id", pJson["external_id"], err, true))
            return false;
    }
    if(pJson.isMember("transaction_date"))
    {
        if(!validJsonOfField(7, "transaction_date", pJson["transaction_date"], err, true))
            return false;
    }
    else
    {
        err="The transaction_date column cannot be null";
        return false;
    }
    if(pJson.isMember("transaction_type_enum"))
    {
        if(!validJsonOfField(8, "transaction_type_enum", pJson["transaction_type_enum"], err, true))
            return false;
    }
    else
    {
        err="The transaction_type_enum column cannot be null";
        return false;
    }
    if(pJson.isMember("amount"))
    {
        if(!validJsonOfField(9, "amount", pJson["amount"], err, true))
            return false;
    }
    else
    {
        err="The amount column cannot be null";
        return false;
    }
    if(pJson.isMember("created_date"))
    {
        if(!validJsonOfField(10, "created_date", pJson["created_date"], err, true))
            return false;
    }
    if(pJson.isMember("created_on_utc"))
    {
        if(!validJsonOfField(11, "created_on_utc", pJson["created_on_utc"], err, true))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(12, "created_by", pJson["created_by"], err, true))
            return false;
    }
    else
    {
        err="The created_by column cannot be null";
        return false;
    }
    if(pJson.isMember("last_modified_by"))
    {
        if(!validJsonOfField(13, "last_modified_by", pJson["last_modified_by"], err, true))
            return false;
    }
    else
    {
        err="The last_modified_by column cannot be null";
        return false;
    }
    if(pJson.isMember("last_modified_on_utc"))
    {
        if(!validJsonOfField(14, "last_modified_on_utc", pJson["last_modified_on_utc"], err, true))
            return false;
    }
    if(pJson.isMember("submitted_on_date"))
    {
        if(!validJsonOfField(15, "submitted_on_date", pJson["submitted_on_date"], err, true))
            return false;
    }
    else
    {
        err="The submitted_on_date column cannot be null";
        return false;
    }
    return true;
}
bool ClientTransaction::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 16)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[9] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[12] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[13] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[15].empty())
      {
          if(pJson.isMember(pMasqueradingVector[15]))
          {
              if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[15] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ClientTransaction::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, false))
            return false;
    }
    if(pJson.isMember("office_id"))
    {
        if(!validJsonOfField(2, "office_id", pJson["office_id"], err, false))
            return false;
    }
    if(pJson.isMember("currency_code"))
    {
        if(!validJsonOfField(3, "currency_code", pJson["currency_code"], err, false))
            return false;
    }
    if(pJson.isMember("payment_detail_id"))
    {
        if(!validJsonOfField(4, "payment_detail_id", pJson["payment_detail_id"], err, false))
            return false;
    }
    if(pJson.isMember("is_reversed"))
    {
        if(!validJsonOfField(5, "is_reversed", pJson["is_reversed"], err, false))
            return false;
    }
    if(pJson.isMember("external_id"))
    {
        if(!validJsonOfField(6, "external_id", pJson["external_id"], err, false))
            return false;
    }
    if(pJson.isMember("transaction_date"))
    {
        if(!validJsonOfField(7, "transaction_date", pJson["transaction_date"], err, false))
            return false;
    }
    if(pJson.isMember("transaction_type_enum"))
    {
        if(!validJsonOfField(8, "transaction_type_enum", pJson["transaction_type_enum"], err, false))
            return false;
    }
    if(pJson.isMember("amount"))
    {
        if(!validJsonOfField(9, "amount", pJson["amount"], err, false))
            return false;
    }
    if(pJson.isMember("created_date"))
    {
        if(!validJsonOfField(10, "created_date", pJson["created_date"], err, false))
            return false;
    }
    if(pJson.isMember("created_on_utc"))
    {
        if(!validJsonOfField(11, "created_on_utc", pJson["created_on_utc"], err, false))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(12, "created_by", pJson["created_by"], err, false))
            return false;
    }
    if(pJson.isMember("last_modified_by"))
    {
        if(!validJsonOfField(13, "last_modified_by", pJson["last_modified_by"], err, false))
            return false;
    }
    if(pJson.isMember("last_modified_on_utc"))
    {
        if(!validJsonOfField(14, "last_modified_on_utc", pJson["last_modified_on_utc"], err, false))
            return false;
    }
    if(pJson.isMember("submitted_on_date"))
    {
        if(!validJsonOfField(15, "submitted_on_date", pJson["submitted_on_date"], err, false))
            return false;
    }
    return true;
}
bool ClientTransaction::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 16)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
      if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
      {
          if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ClientTransaction::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 15:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
