/**
 *
 *  LoanDisbursementDetail.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "LoanDisbursementDetail.h"
#include "Loan.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::TlPortfolioDb;

const std::string LoanDisbursementDetail::Cols::_id = "\"id\"";
const std::string LoanDisbursementDetail::Cols::_loan_id = "\"loan_id\"";
const std::string LoanDisbursementDetail::Cols::_expected_disburse_date = "\"expected_disburse_date\"";
const std::string LoanDisbursementDetail::Cols::_actual_disburse_date = "\"actual_disburse_date\"";
const std::string LoanDisbursementDetail::Cols::_principal = "\"principal\"";
const std::string LoanDisbursementDetail::primaryKeyName = "id";
const bool LoanDisbursementDetail::hasPrimaryKey = true;
const std::string LoanDisbursementDetail::tableName = "\"loan_disbursement_detail\"";

const std::vector<typename LoanDisbursementDetail::MetaData> LoanDisbursementDetail::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"loan_id","std::string","uuid",0,0,0,1},
{"expected_disburse_date","::trantor::Date","date",0,0,0,1},
{"actual_disburse_date","::trantor::Date","date",0,0,0,0},
{"principal","std::string","numeric",0,0,0,1}
};
const std::string &LoanDisbursementDetail::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
LoanDisbursementDetail::LoanDisbursementDetail(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["loan_id"].isNull())
        {
            loanId_=std::make_shared<std::string>(r["loan_id"].as<std::string>());
        }
        if(!r["expected_disburse_date"].isNull())
        {
            auto daysStr = r["expected_disburse_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            expectedDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["actual_disburse_date"].isNull())
        {
            auto daysStr = r["actual_disburse_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            actualDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["principal"].isNull())
        {
            principal_=std::make_shared<std::string>(r["principal"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            loanId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            expectedDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            actualDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            principal_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

LoanDisbursementDetail::LoanDisbursementDetail(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            loanId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            expectedDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            actualDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            principal_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

LoanDisbursementDetail::LoanDisbursementDetail(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("loan_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["loan_id"].isNull())
        {
            loanId_=std::make_shared<std::string>(pJson["loan_id"].asString());
        }
    }
    if(pJson.isMember("expected_disburse_date"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["expected_disburse_date"].isNull())
        {
            auto daysStr = pJson["expected_disburse_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            expectedDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("actual_disburse_date"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["actual_disburse_date"].isNull())
        {
            auto daysStr = pJson["actual_disburse_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            actualDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("principal"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["principal"].isNull())
        {
            principal_=std::make_shared<std::string>(pJson["principal"].asString());
        }
    }
}

void LoanDisbursementDetail::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            loanId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            expectedDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            actualDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            principal_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void LoanDisbursementDetail::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("loan_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["loan_id"].isNull())
        {
            loanId_=std::make_shared<std::string>(pJson["loan_id"].asString());
        }
    }
    if(pJson.isMember("expected_disburse_date"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["expected_disburse_date"].isNull())
        {
            auto daysStr = pJson["expected_disburse_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            expectedDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("actual_disburse_date"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["actual_disburse_date"].isNull())
        {
            auto daysStr = pJson["actual_disburse_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            actualDisburseDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("principal"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["principal"].isNull())
        {
            principal_=std::make_shared<std::string>(pJson["principal"].asString());
        }
    }
}

const std::string &LoanDisbursementDetail::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LoanDisbursementDetail::getId() const noexcept
{
    return id_;
}
void LoanDisbursementDetail::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void LoanDisbursementDetail::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename LoanDisbursementDetail::PrimaryKeyType & LoanDisbursementDetail::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &LoanDisbursementDetail::getValueOfLoanId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(loanId_)
        return *loanId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LoanDisbursementDetail::getLoanId() const noexcept
{
    return loanId_;
}
void LoanDisbursementDetail::setLoanId(const std::string &pLoanId) noexcept
{
    loanId_ = std::make_shared<std::string>(pLoanId);
    dirtyFlag_[1] = true;
}
void LoanDisbursementDetail::setLoanId(std::string &&pLoanId) noexcept
{
    loanId_ = std::make_shared<std::string>(std::move(pLoanId));
    dirtyFlag_[1] = true;
}

const ::trantor::Date &LoanDisbursementDetail::getValueOfExpectedDisburseDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(expectedDisburseDate_)
        return *expectedDisburseDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &LoanDisbursementDetail::getExpectedDisburseDate() const noexcept
{
    return expectedDisburseDate_;
}
void LoanDisbursementDetail::setExpectedDisburseDate(const ::trantor::Date &pExpectedDisburseDate) noexcept
{
    expectedDisburseDate_ = std::make_shared<::trantor::Date>(pExpectedDisburseDate.roundDay());
    dirtyFlag_[2] = true;
}

const ::trantor::Date &LoanDisbursementDetail::getValueOfActualDisburseDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(actualDisburseDate_)
        return *actualDisburseDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &LoanDisbursementDetail::getActualDisburseDate() const noexcept
{
    return actualDisburseDate_;
}
void LoanDisbursementDetail::setActualDisburseDate(const ::trantor::Date &pActualDisburseDate) noexcept
{
    actualDisburseDate_ = std::make_shared<::trantor::Date>(pActualDisburseDate.roundDay());
    dirtyFlag_[3] = true;
}
void LoanDisbursementDetail::setActualDisburseDateToNull() noexcept
{
    actualDisburseDate_.reset();
    dirtyFlag_[3] = true;
}

const std::string &LoanDisbursementDetail::getValueOfPrincipal() const noexcept
{
    static const std::string defaultValue = std::string();
    if(principal_)
        return *principal_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LoanDisbursementDetail::getPrincipal() const noexcept
{
    return principal_;
}
void LoanDisbursementDetail::setPrincipal(const std::string &pPrincipal) noexcept
{
    principal_ = std::make_shared<std::string>(pPrincipal);
    dirtyFlag_[4] = true;
}
void LoanDisbursementDetail::setPrincipal(std::string &&pPrincipal) noexcept
{
    principal_ = std::make_shared<std::string>(std::move(pPrincipal));
    dirtyFlag_[4] = true;
}

void LoanDisbursementDetail::updateId(const uint64_t id)
{
}

const std::vector<std::string> &LoanDisbursementDetail::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "loan_id",
        "expected_disburse_date",
        "actual_disburse_date",
        "principal"
    };
    return inCols;
}

void LoanDisbursementDetail::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getLoanId())
        {
            binder << getValueOfLoanId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getExpectedDisburseDate())
        {
            binder << getValueOfExpectedDisburseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getActualDisburseDate())
        {
            binder << getValueOfActualDisburseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrincipal())
        {
            binder << getValueOfPrincipal();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> LoanDisbursementDetail::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void LoanDisbursementDetail::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getLoanId())
        {
            binder << getValueOfLoanId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getExpectedDisburseDate())
        {
            binder << getValueOfExpectedDisburseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getActualDisburseDate())
        {
            binder << getValueOfActualDisburseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrincipal())
        {
            binder << getValueOfPrincipal();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value LoanDisbursementDetail::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getLoanId())
    {
        ret["loan_id"]=getValueOfLoanId();
    }
    else
    {
        ret["loan_id"]=Json::Value();
    }
    if(getExpectedDisburseDate())
    {
        ret["expected_disburse_date"]=getExpectedDisburseDate()->toDbStringLocal();
    }
    else
    {
        ret["expected_disburse_date"]=Json::Value();
    }
    if(getActualDisburseDate())
    {
        ret["actual_disburse_date"]=getActualDisburseDate()->toDbStringLocal();
    }
    else
    {
        ret["actual_disburse_date"]=Json::Value();
    }
    if(getPrincipal())
    {
        ret["principal"]=getValueOfPrincipal();
    }
    else
    {
        ret["principal"]=Json::Value();
    }
    return ret;
}

std::string LoanDisbursementDetail::toString() const
{
    return toJson().toStyledString();
}

Json::Value LoanDisbursementDetail::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getLoanId())
            {
                ret[pMasqueradingVector[1]]=getValueOfLoanId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getExpectedDisburseDate())
            {
                ret[pMasqueradingVector[2]]=getExpectedDisburseDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getActualDisburseDate())
            {
                ret[pMasqueradingVector[3]]=getActualDisburseDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPrincipal())
            {
                ret[pMasqueradingVector[4]]=getValueOfPrincipal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getLoanId())
    {
        ret["loan_id"]=getValueOfLoanId();
    }
    else
    {
        ret["loan_id"]=Json::Value();
    }
    if(getExpectedDisburseDate())
    {
        ret["expected_disburse_date"]=getExpectedDisburseDate()->toDbStringLocal();
    }
    else
    {
        ret["expected_disburse_date"]=Json::Value();
    }
    if(getActualDisburseDate())
    {
        ret["actual_disburse_date"]=getActualDisburseDate()->toDbStringLocal();
    }
    else
    {
        ret["actual_disburse_date"]=Json::Value();
    }
    if(getPrincipal())
    {
        ret["principal"]=getValueOfPrincipal();
    }
    else
    {
        ret["principal"]=Json::Value();
    }
    return ret;
}

bool LoanDisbursementDetail::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("loan_id"))
    {
        if(!validJsonOfField(1, "loan_id", pJson["loan_id"], err, true))
            return false;
    }
    else
    {
        err="The loan_id column cannot be null";
        return false;
    }
    if(pJson.isMember("expected_disburse_date"))
    {
        if(!validJsonOfField(2, "expected_disburse_date", pJson["expected_disburse_date"], err, true))
            return false;
    }
    else
    {
        err="The expected_disburse_date column cannot be null";
        return false;
    }
    if(pJson.isMember("actual_disburse_date"))
    {
        if(!validJsonOfField(3, "actual_disburse_date", pJson["actual_disburse_date"], err, true))
            return false;
    }
    if(pJson.isMember("principal"))
    {
        if(!validJsonOfField(4, "principal", pJson["principal"], err, true))
            return false;
    }
    else
    {
        err="The principal column cannot be null";
        return false;
    }
    return true;
}
bool LoanDisbursementDetail::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                const std::vector<std::string> &pMasqueradingVector,
                                                                std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LoanDisbursementDetail::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("loan_id"))
    {
        if(!validJsonOfField(1, "loan_id", pJson["loan_id"], err, false))
            return false;
    }
    if(pJson.isMember("expected_disburse_date"))
    {
        if(!validJsonOfField(2, "expected_disburse_date", pJson["expected_disburse_date"], err, false))
            return false;
    }
    if(pJson.isMember("actual_disburse_date"))
    {
        if(!validJsonOfField(3, "actual_disburse_date", pJson["actual_disburse_date"], err, false))
            return false;
    }
    if(pJson.isMember("principal"))
    {
        if(!validJsonOfField(4, "principal", pJson["principal"], err, false))
            return false;
    }
    return true;
}
bool LoanDisbursementDetail::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                              const std::vector<std::string> &pMasqueradingVector,
                                                              std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LoanDisbursementDetail::validJsonOfField(size_t index,
                                              const std::string &fieldName,
                                              const Json::Value &pJson,
                                              std::string &err,
                                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Loan LoanDisbursementDetail::getLoan(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from loan where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *loanId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Loan(r[0]);
}

void LoanDisbursementDetail::getLoan(const DbClientPtr &clientPtr,
                                     const std::function<void(Loan)> &rcb,
                                     const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from loan where id = $1";
    *clientPtr << sql
               << *loanId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Loan(r[0]));
                    }
               }
               >> ecb;
}
