/**
 *
 *  SharePurchaseRequest.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace TlPortfolioDb
{
class ShareAccount;

class SharePurchaseRequest
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _share_account_id;
        static const std::string _requested_date;
        static const std::string _requested_shares;
        static const std::string _requested_price;
        static const std::string _status;
        static const std::string _requested_by;
        static const std::string _decided_by;
        static const std::string _decided_date;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit SharePurchaseRequest(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit SharePurchaseRequest(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    SharePurchaseRequest(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    SharePurchaseRequest() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column share_account_id  */
    ///Get the value of the column share_account_id, returns the default value if the column is null
    const std::string &getValueOfShareAccountId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getShareAccountId() const noexcept;
    ///Set the value of the column share_account_id
    void setShareAccountId(const std::string &pShareAccountId) noexcept;
    void setShareAccountId(std::string &&pShareAccountId) noexcept;

    /**  For column requested_date  */
    ///Get the value of the column requested_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfRequestedDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getRequestedDate() const noexcept;
    ///Set the value of the column requested_date
    void setRequestedDate(const ::trantor::Date &pRequestedDate) noexcept;

    /**  For column requested_shares  */
    ///Get the value of the column requested_shares, returns the default value if the column is null
    const int64_t &getValueOfRequestedShares() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getRequestedShares() const noexcept;
    ///Set the value of the column requested_shares
    void setRequestedShares(const int64_t &pRequestedShares) noexcept;

    /**  For column requested_price  */
    ///Get the value of the column requested_price, returns the default value if the column is null
    const std::string &getValueOfRequestedPrice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRequestedPrice() const noexcept;
    ///Set the value of the column requested_price
    void setRequestedPrice(const std::string &pRequestedPrice) noexcept;
    void setRequestedPrice(std::string &&pRequestedPrice) noexcept;
    void setRequestedPriceToNull() noexcept;

    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const int32_t &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getStatus() const noexcept;
    ///Set the value of the column status
    void setStatus(const int32_t &pStatus) noexcept;

    /**  For column requested_by  */
    ///Get the value of the column requested_by, returns the default value if the column is null
    const std::string &getValueOfRequestedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRequestedBy() const noexcept;
    ///Set the value of the column requested_by
    void setRequestedBy(const std::string &pRequestedBy) noexcept;
    void setRequestedBy(std::string &&pRequestedBy) noexcept;
    void setRequestedByToNull() noexcept;

    /**  For column decided_by  */
    ///Get the value of the column decided_by, returns the default value if the column is null
    const std::string &getValueOfDecidedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDecidedBy() const noexcept;
    ///Set the value of the column decided_by
    void setDecidedBy(const std::string &pDecidedBy) noexcept;
    void setDecidedBy(std::string &&pDecidedBy) noexcept;
    void setDecidedByToNull() noexcept;

    /**  For column decided_date  */
    ///Get the value of the column decided_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfDecidedDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDecidedDate() const noexcept;
    ///Set the value of the column decided_date
    void setDecidedDate(const ::trantor::Date &pDecidedDate) noexcept;
    void setDecidedDateToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 10;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    ShareAccount getShareAccount(const drogon::orm::DbClientPtr &clientPtr) const;
    void getShareAccount(const drogon::orm::DbClientPtr &clientPtr,
                         const std::function<void(ShareAccount)> &rcb,
                         const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<SharePurchaseRequest>;
    friend drogon::orm::BaseBuilder<SharePurchaseRequest, true, true>;
    friend drogon::orm::BaseBuilder<SharePurchaseRequest, true, false>;
    friend drogon::orm::BaseBuilder<SharePurchaseRequest, false, true>;
    friend drogon::orm::BaseBuilder<SharePurchaseRequest, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<SharePurchaseRequest>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> shareAccountId_;
    std::shared_ptr<::trantor::Date> requestedDate_;
    std::shared_ptr<int64_t> requestedShares_;
    std::shared_ptr<std::string> requestedPrice_;
    std::shared_ptr<int32_t> status_;
    std::shared_ptr<std::string> requestedBy_;
    std::shared_ptr<std::string> decidedBy_;
    std::shared_ptr<::trantor::Date> decidedDate_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[10]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "share_account_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "requested_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "requested_shares,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "requested_price,";
            ++parametersCount;
        }
        sql += "status,";
        ++parametersCount;
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        if(dirtyFlag_[6])
        {
            sql += "requested_by,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "decided_by,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "decided_date,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace TlPortfolioDb
} // namespace drogon_model
