/**
 *
 *  TlImage.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TlImage.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::TlSystemConfigDb;

const std::string TlImage::Cols::_entity_type = "\"entity_type\"";
const std::string TlImage::Cols::_entity_id = "\"entity_id\"";
const std::string TlImage::Cols::_content_type = "\"content_type\"";
const std::string TlImage::Cols::_content = "\"content\"";
const std::string TlImage::Cols::_modified_at = "\"modified_at\"";
const std::vector<std::string> TlImage::primaryKeyName = {"entity_type","entity_id"};
const bool TlImage::hasPrimaryKey = true;
const std::string TlImage::tableName = "\"tl_image\"";

const std::vector<typename TlImage::MetaData> TlImage::metaData_={
{"entity_type","std::string","character varying",60,0,1,1},
{"entity_id","std::string","character varying",80,0,1,1},
{"content_type","std::string","character varying",120,0,0,0},
{"content","std::vector<char>","bytea",0,0,0,1},
{"modified_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &TlImage::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TlImage::TlImage(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["entity_type"].isNull())
        {
            entityType_=std::make_shared<std::string>(r["entity_type"].as<std::string>());
        }
        if(!r["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(r["entity_id"].as<std::string>());
        }
        if(!r["content_type"].isNull())
        {
            contentType_=std::make_shared<std::string>(r["content_type"].as<std::string>());
        }
        if(!r["content"].isNull())
        {
            auto str = r["content"].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                content_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        if(!r["modified_at"].isNull())
        {
            auto timeStr = r["modified_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            entityType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            entityId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            contentType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto str = r[index].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                content_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

TlImage::TlImage(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            contentType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto str = pJson[pMasqueradingVector[3]].asString();
            content_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

TlImage::TlImage(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("entity_type"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["entity_type"].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson["entity_type"].asString());
        }
    }
    if(pJson.isMember("entity_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson["entity_id"].asString());
        }
    }
    if(pJson.isMember("content_type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["content_type"].isNull())
        {
            contentType_=std::make_shared<std::string>(pJson["content_type"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["content"].isNull())
        {
            auto str = pJson["content"].asString();
            content_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("modified_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["modified_at"].isNull())
        {
            auto timeStr = pJson["modified_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void TlImage::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            contentType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto str = pJson[pMasqueradingVector[3]].asString();
            content_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void TlImage::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("entity_type"))
    {
        if(!pJson["entity_type"].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson["entity_type"].asString());
        }
    }
    if(pJson.isMember("entity_id"))
    {
        if(!pJson["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson["entity_id"].asString());
        }
    }
    if(pJson.isMember("content_type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["content_type"].isNull())
        {
            contentType_=std::make_shared<std::string>(pJson["content_type"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["content"].isNull())
        {
            auto str = pJson["content"].asString();
            content_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("modified_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["modified_at"].isNull())
        {
            auto timeStr = pJson["modified_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &TlImage::getValueOfEntityType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(entityType_)
        return *entityType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TlImage::getEntityType() const noexcept
{
    return entityType_;
}
void TlImage::setEntityType(const std::string &pEntityType) noexcept
{
    entityType_ = std::make_shared<std::string>(pEntityType);
    dirtyFlag_[0] = true;
}
void TlImage::setEntityType(std::string &&pEntityType) noexcept
{
    entityType_ = std::make_shared<std::string>(std::move(pEntityType));
    dirtyFlag_[0] = true;
}

const std::string &TlImage::getValueOfEntityId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(entityId_)
        return *entityId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TlImage::getEntityId() const noexcept
{
    return entityId_;
}
void TlImage::setEntityId(const std::string &pEntityId) noexcept
{
    entityId_ = std::make_shared<std::string>(pEntityId);
    dirtyFlag_[1] = true;
}
void TlImage::setEntityId(std::string &&pEntityId) noexcept
{
    entityId_ = std::make_shared<std::string>(std::move(pEntityId));
    dirtyFlag_[1] = true;
}

const std::string &TlImage::getValueOfContentType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(contentType_)
        return *contentType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TlImage::getContentType() const noexcept
{
    return contentType_;
}
void TlImage::setContentType(const std::string &pContentType) noexcept
{
    contentType_ = std::make_shared<std::string>(pContentType);
    dirtyFlag_[2] = true;
}
void TlImage::setContentType(std::string &&pContentType) noexcept
{
    contentType_ = std::make_shared<std::string>(std::move(pContentType));
    dirtyFlag_[2] = true;
}
void TlImage::setContentTypeToNull() noexcept
{
    contentType_.reset();
    dirtyFlag_[2] = true;
}

const std::vector<char> &TlImage::getValueOfContent() const noexcept
{
    static const std::vector<char> defaultValue = std::vector<char>();
    if(content_)
        return *content_;
    return defaultValue;
}
std::string TlImage::getValueOfContentAsString() const noexcept
{
    static const std::string defaultValue = std::string();
    if(content_)
        return std::string(content_->data(),content_->size());
    return defaultValue;
}
const std::shared_ptr<std::vector<char>> &TlImage::getContent() const noexcept
{
    return content_;
}
void TlImage::setContent(const std::vector<char> &pContent) noexcept
{
    content_ = std::make_shared<std::vector<char>>(pContent);
    dirtyFlag_[3] = true;
}
void TlImage::setContent(const std::string &pContent) noexcept
{
    content_ = std::make_shared<std::vector<char>>(pContent.c_str(),pContent.c_str()+pContent.length());
    dirtyFlag_[3] = true;
}

const ::trantor::Date &TlImage::getValueOfModifiedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(modifiedAt_)
        return *modifiedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TlImage::getModifiedAt() const noexcept
{
    return modifiedAt_;
}
void TlImage::setModifiedAt(const ::trantor::Date &pModifiedAt) noexcept
{
    modifiedAt_ = std::make_shared<::trantor::Date>(pModifiedAt);
    dirtyFlag_[4] = true;
}

void TlImage::updateId(const uint64_t id)
{
}
typename TlImage::PrimaryKeyType TlImage::getPrimaryKey() const
{
    return std::make_tuple(*entityType_,*entityId_);
}

const std::vector<std::string> &TlImage::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "entity_type",
        "entity_id",
        "content_type",
        "content",
        "modified_at"
    };
    return inCols;
}

void TlImage::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getEntityType())
        {
            binder << getValueOfEntityType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getEntityId())
        {
            binder << getValueOfEntityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getContentType())
        {
            binder << getValueOfContentType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getModifiedAt())
        {
            binder << getValueOfModifiedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TlImage::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void TlImage::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getEntityType())
        {
            binder << getValueOfEntityType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getEntityId())
        {
            binder << getValueOfEntityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getContentType())
        {
            binder << getValueOfContentType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getModifiedAt())
        {
            binder << getValueOfModifiedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TlImage::toJson() const
{
    Json::Value ret;
    if(getEntityType())
    {
        ret["entity_type"]=getValueOfEntityType();
    }
    else
    {
        ret["entity_type"]=Json::Value();
    }
    if(getEntityId())
    {
        ret["entity_id"]=getValueOfEntityId();
    }
    else
    {
        ret["entity_id"]=Json::Value();
    }
    if(getContentType())
    {
        ret["content_type"]=getValueOfContentType();
    }
    else
    {
        ret["content_type"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=drogon::utils::base64Encode((const unsigned char *)getContent()->data(),getContent()->size());
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getModifiedAt())
    {
        ret["modified_at"]=getModifiedAt()->toDbStringLocal();
    }
    else
    {
        ret["modified_at"]=Json::Value();
    }
    return ret;
}

std::string TlImage::toString() const
{
    return toJson().toStyledString();
}

Json::Value TlImage::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getEntityType())
            {
                ret[pMasqueradingVector[0]]=getValueOfEntityType();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getEntityId())
            {
                ret[pMasqueradingVector[1]]=getValueOfEntityId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getContentType())
            {
                ret[pMasqueradingVector[2]]=getValueOfContentType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getContent())
            {
                ret[pMasqueradingVector[3]]=drogon::utils::base64Encode((const unsigned char *)getContent()->data(),getContent()->size());
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getModifiedAt())
            {
                ret[pMasqueradingVector[4]]=getModifiedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getEntityType())
    {
        ret["entity_type"]=getValueOfEntityType();
    }
    else
    {
        ret["entity_type"]=Json::Value();
    }
    if(getEntityId())
    {
        ret["entity_id"]=getValueOfEntityId();
    }
    else
    {
        ret["entity_id"]=Json::Value();
    }
    if(getContentType())
    {
        ret["content_type"]=getValueOfContentType();
    }
    else
    {
        ret["content_type"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=drogon::utils::base64Encode((const unsigned char *)getContent()->data(),getContent()->size());
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getModifiedAt())
    {
        ret["modified_at"]=getModifiedAt()->toDbStringLocal();
    }
    else
    {
        ret["modified_at"]=Json::Value();
    }
    return ret;
}

bool TlImage::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("entity_type"))
    {
        if(!validJsonOfField(0, "entity_type", pJson["entity_type"], err, true))
            return false;
    }
    else
    {
        err="The entity_type column cannot be null";
        return false;
    }
    if(pJson.isMember("entity_id"))
    {
        if(!validJsonOfField(1, "entity_id", pJson["entity_id"], err, true))
            return false;
    }
    else
    {
        err="The entity_id column cannot be null";
        return false;
    }
    if(pJson.isMember("content_type"))
    {
        if(!validJsonOfField(2, "content_type", pJson["content_type"], err, true))
            return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(3, "content", pJson["content"], err, true))
            return false;
    }
    else
    {
        err="The content column cannot be null";
        return false;
    }
    if(pJson.isMember("modified_at"))
    {
        if(!validJsonOfField(4, "modified_at", pJson["modified_at"], err, true))
            return false;
    }
    return true;
}
bool TlImage::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TlImage::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("entity_type"))
    {
        if(!validJsonOfField(0, "entity_type", pJson["entity_type"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("entity_id"))
    {
        if(!validJsonOfField(1, "entity_id", pJson["entity_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("content_type"))
    {
        if(!validJsonOfField(2, "content_type", pJson["content_type"], err, false))
            return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(3, "content", pJson["content"], err, false))
            return false;
    }
    if(pJson.isMember("modified_at"))
    {
        if(!validJsonOfField(4, "modified_at", pJson["modified_at"], err, false))
            return false;
    }
    return true;
}
bool TlImage::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TlImage::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 60)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 60)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 80)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 80)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 120)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 120)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
