/**
 *
 *  JournalEntryDetails.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "JournalEntryDetails.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::TurboLedgerAccounting;

const std::string JournalEntryDetails::Cols::_id = "\"id\"";
const std::string JournalEntryDetails::Cols::_journal_entry_id = "\"journal_entry_id\"";
const std::string JournalEntryDetails::Cols::_account_id = "\"account_id\"";
const std::string JournalEntryDetails::Cols::_debit = "\"debit\"";
const std::string JournalEntryDetails::Cols::_credit = "\"credit\"";
const std::string JournalEntryDetails::primaryKeyName = "id";
const bool JournalEntryDetails::hasPrimaryKey = true;
const std::string JournalEntryDetails::tableName = "\"journal_entry_details\"";

const std::vector<typename JournalEntryDetails::MetaData> JournalEntryDetails::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"journal_entry_id","std::string","uuid",0,0,0,1},
{"account_id","std::string","uuid",0,0,0,1},
{"debit","std::string","numeric",0,0,0,1},
{"credit","std::string","numeric",0,0,0,1}
};
const std::string &JournalEntryDetails::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
JournalEntryDetails::JournalEntryDetails(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["journal_entry_id"].isNull())
        {
            journalEntryId_=std::make_shared<std::string>(r["journal_entry_id"].as<std::string>());
        }
        if(!r["account_id"].isNull())
        {
            accountId_=std::make_shared<std::string>(r["account_id"].as<std::string>());
        }
        if(!r["debit"].isNull())
        {
            debit_=std::make_shared<std::string>(r["debit"].as<std::string>());
        }
        if(!r["credit"].isNull())
        {
            credit_=std::make_shared<std::string>(r["credit"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            journalEntryId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            accountId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            debit_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            credit_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

JournalEntryDetails::JournalEntryDetails(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            journalEntryId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            accountId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            debit_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            credit_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

JournalEntryDetails::JournalEntryDetails(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("journal_entry_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["journal_entry_id"].isNull())
        {
            journalEntryId_=std::make_shared<std::string>(pJson["journal_entry_id"].asString());
        }
    }
    if(pJson.isMember("account_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<std::string>(pJson["account_id"].asString());
        }
    }
    if(pJson.isMember("debit"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["debit"].isNull())
        {
            debit_=std::make_shared<std::string>(pJson["debit"].asString());
        }
    }
    if(pJson.isMember("credit"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["credit"].isNull())
        {
            credit_=std::make_shared<std::string>(pJson["credit"].asString());
        }
    }
}

void JournalEntryDetails::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            journalEntryId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            accountId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            debit_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            credit_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void JournalEntryDetails::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("journal_entry_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["journal_entry_id"].isNull())
        {
            journalEntryId_=std::make_shared<std::string>(pJson["journal_entry_id"].asString());
        }
    }
    if(pJson.isMember("account_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<std::string>(pJson["account_id"].asString());
        }
    }
    if(pJson.isMember("debit"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["debit"].isNull())
        {
            debit_=std::make_shared<std::string>(pJson["debit"].asString());
        }
    }
    if(pJson.isMember("credit"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["credit"].isNull())
        {
            credit_=std::make_shared<std::string>(pJson["credit"].asString());
        }
    }
}

const std::string &JournalEntryDetails::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &JournalEntryDetails::getId() const noexcept
{
    return id_;
}
void JournalEntryDetails::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void JournalEntryDetails::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename JournalEntryDetails::PrimaryKeyType & JournalEntryDetails::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &JournalEntryDetails::getValueOfJournalEntryId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(journalEntryId_)
        return *journalEntryId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &JournalEntryDetails::getJournalEntryId() const noexcept
{
    return journalEntryId_;
}
void JournalEntryDetails::setJournalEntryId(const std::string &pJournalEntryId) noexcept
{
    journalEntryId_ = std::make_shared<std::string>(pJournalEntryId);
    dirtyFlag_[1] = true;
}
void JournalEntryDetails::setJournalEntryId(std::string &&pJournalEntryId) noexcept
{
    journalEntryId_ = std::make_shared<std::string>(std::move(pJournalEntryId));
    dirtyFlag_[1] = true;
}

const std::string &JournalEntryDetails::getValueOfAccountId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(accountId_)
        return *accountId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &JournalEntryDetails::getAccountId() const noexcept
{
    return accountId_;
}
void JournalEntryDetails::setAccountId(const std::string &pAccountId) noexcept
{
    accountId_ = std::make_shared<std::string>(pAccountId);
    dirtyFlag_[2] = true;
}
void JournalEntryDetails::setAccountId(std::string &&pAccountId) noexcept
{
    accountId_ = std::make_shared<std::string>(std::move(pAccountId));
    dirtyFlag_[2] = true;
}

const std::string &JournalEntryDetails::getValueOfDebit() const noexcept
{
    static const std::string defaultValue = std::string();
    if(debit_)
        return *debit_;
    return defaultValue;
}
const std::shared_ptr<std::string> &JournalEntryDetails::getDebit() const noexcept
{
    return debit_;
}
void JournalEntryDetails::setDebit(const std::string &pDebit) noexcept
{
    debit_ = std::make_shared<std::string>(pDebit);
    dirtyFlag_[3] = true;
}
void JournalEntryDetails::setDebit(std::string &&pDebit) noexcept
{
    debit_ = std::make_shared<std::string>(std::move(pDebit));
    dirtyFlag_[3] = true;
}

const std::string &JournalEntryDetails::getValueOfCredit() const noexcept
{
    static const std::string defaultValue = std::string();
    if(credit_)
        return *credit_;
    return defaultValue;
}
const std::shared_ptr<std::string> &JournalEntryDetails::getCredit() const noexcept
{
    return credit_;
}
void JournalEntryDetails::setCredit(const std::string &pCredit) noexcept
{
    credit_ = std::make_shared<std::string>(pCredit);
    dirtyFlag_[4] = true;
}
void JournalEntryDetails::setCredit(std::string &&pCredit) noexcept
{
    credit_ = std::make_shared<std::string>(std::move(pCredit));
    dirtyFlag_[4] = true;
}

void JournalEntryDetails::updateId(const uint64_t id)
{
}

const std::vector<std::string> &JournalEntryDetails::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "journal_entry_id",
        "account_id",
        "debit",
        "credit"
    };
    return inCols;
}

void JournalEntryDetails::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getJournalEntryId())
        {
            binder << getValueOfJournalEntryId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDebit())
        {
            binder << getValueOfDebit();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCredit())
        {
            binder << getValueOfCredit();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> JournalEntryDetails::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void JournalEntryDetails::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getJournalEntryId())
        {
            binder << getValueOfJournalEntryId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDebit())
        {
            binder << getValueOfDebit();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCredit())
        {
            binder << getValueOfCredit();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value JournalEntryDetails::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getJournalEntryId())
    {
        ret["journal_entry_id"]=getValueOfJournalEntryId();
    }
    else
    {
        ret["journal_entry_id"]=Json::Value();
    }
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    if(getDebit())
    {
        ret["debit"]=getValueOfDebit();
    }
    else
    {
        ret["debit"]=Json::Value();
    }
    if(getCredit())
    {
        ret["credit"]=getValueOfCredit();
    }
    else
    {
        ret["credit"]=Json::Value();
    }
    return ret;
}

std::string JournalEntryDetails::toString() const
{
    return toJson().toStyledString();
}

Json::Value JournalEntryDetails::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getJournalEntryId())
            {
                ret[pMasqueradingVector[1]]=getValueOfJournalEntryId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAccountId())
            {
                ret[pMasqueradingVector[2]]=getValueOfAccountId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDebit())
            {
                ret[pMasqueradingVector[3]]=getValueOfDebit();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCredit())
            {
                ret[pMasqueradingVector[4]]=getValueOfCredit();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getJournalEntryId())
    {
        ret["journal_entry_id"]=getValueOfJournalEntryId();
    }
    else
    {
        ret["journal_entry_id"]=Json::Value();
    }
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    if(getDebit())
    {
        ret["debit"]=getValueOfDebit();
    }
    else
    {
        ret["debit"]=Json::Value();
    }
    if(getCredit())
    {
        ret["credit"]=getValueOfCredit();
    }
    else
    {
        ret["credit"]=Json::Value();
    }
    return ret;
}

bool JournalEntryDetails::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("journal_entry_id"))
    {
        if(!validJsonOfField(1, "journal_entry_id", pJson["journal_entry_id"], err, true))
            return false;
    }
    else
    {
        err="The journal_entry_id column cannot be null";
        return false;
    }
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(2, "account_id", pJson["account_id"], err, true))
            return false;
    }
    else
    {
        err="The account_id column cannot be null";
        return false;
    }
    if(pJson.isMember("debit"))
    {
        if(!validJsonOfField(3, "debit", pJson["debit"], err, true))
            return false;
    }
    if(pJson.isMember("credit"))
    {
        if(!validJsonOfField(4, "credit", pJson["credit"], err, true))
            return false;
    }
    return true;
}
bool JournalEntryDetails::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool JournalEntryDetails::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("journal_entry_id"))
    {
        if(!validJsonOfField(1, "journal_entry_id", pJson["journal_entry_id"], err, false))
            return false;
    }
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(2, "account_id", pJson["account_id"], err, false))
            return false;
    }
    if(pJson.isMember("debit"))
    {
        if(!validJsonOfField(3, "debit", pJson["debit"], err, false))
            return false;
    }
    if(pJson.isMember("credit"))
    {
        if(!validJsonOfField(4, "credit", pJson["credit"], err, false))
            return false;
    }
    return true;
}
bool JournalEntryDetails::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool JournalEntryDetails::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson,
                                           std::string &err,
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
